

function ΔrTextShape() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AAPBAIAQg2QADgKAAgEQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAAAAAAAIgFgBIgIAAIAAgDIAfgFIgOAqQAQgaANgKQAHgGAFAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQACACAAAEQAAAFgDAFQgCAEgEgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIgBgCIgCgBIgDABIgHAGQgIAJgHAOQgFAFgCAIIgEAMIgDALgAhgBAIA3h6IAyB6gAhVA4IBLAAIgkhUgABLgwIg0AAIAAgFIA0AAIgEgKIAaAMIgaANg");
	
	return shape
}

function θTextShape() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AgPAqIgDgDIgDgEIgCgFQgBgHABgIIACgPIAFgOQAEgIAFgHIAHgJIAFgDIAGgBIAEABIAFADIACAEIABAFQADAHgCAIIgCAOIgFAPQgDAIgFAHIgJAJIgEADIgFABgAgPAQQgBAGABAHIAAAEIABAEIACADIADAAQADAAADgDIAFgIIAHgNIADgOIgYAAgAADgkIgEAIQgEAGgCAHIgEAOIAYAAIADgOQACgHgBgGIgCgIIgCgCIgDgBQgEAAgDADg");
	
	return shape
}


