/*!
* © by Sitsanlis Ilias
* This notice shall be included in all copies or substantial portions of the Software.
* Creative Commons 4.0/CC BY - NC - SA 4.0. 
*/

$(function(){$("#more").button({text:!0,icons:{primary:"ui-icon-settings"}}).click(function(){$("#dialog").dialog("isOpen")?$("#dialog").dialog("close"):$("#dialog").dialog("open")});$("#energy").button({text:!1}).click(function(){energyFlag=$("#energy").is(":checked");energyContainer.visible=energyFlag;positions()});$("#momentum").button({text:!1}).click(function(){momentumFlag=$("#momentum").is(":checked");momentumContainer.visible=momentumFlag;positions()});$("#stopAtCollision").button({text:!1}).click(function(){stopFlag=
$("#stopAtCollision").is(":checked")})});
$(function(){$("#m1Spinner").spinner({min:1,max:10,step:1,numberFormat:"n",spin:function(a,b){updateValue_m1(a,b.value)},change:function(a){updateValue_m1(a,this.value)}}).val(m1);$("#m1Spinner").keypress(function(a){13==a.which&&(.1>$(this).val()&&$(this).val(.1),a.preventDefault(),updateValue_m1(a,this.value))});$("#m2Spinner").spinner({min:1,max:10,step:1,numberFormat:"n",spin:function(a,b){updateValue_m2(a,b.value)},change:function(a){updateValue_m2(a,this.value)}}).val(m2);$("#m2Spinner").keypress(function(a){13==
a.which&&(.1>$(this).val()&&$(this).val(.1),a.preventDefault(),updateValue_m2(a,this.value))});$("#v1Spinner").spinner({min:-10,max:10,step:1,numberFormat:"n",spin:function(a,b){updateValue_v1(a,b.value)},change:function(a){updateValue_v1(a,this.value)}}).val(v01);$("#v1Spinner").keypress(function(a){13==a.which&&(a.preventDefault(),updateValue_v1(a,this.value))});$("#v2Spinner").spinner({min:-10,max:10,step:1,numberFormat:"n",spin:function(a,b){updateValue_v2(a,b.value)},change:function(a){updateValue_v2(a,
this.value)}}).val(v02);$("#v2Spinner").keypress(function(a){13==a.which&&(a.preventDefault(),updateValue_v2(a,this.value))})});function updateValue_m1(a,b){m1=Number(b);$("#m1Slider").slider({value:b});restart()}function updateValue_m2(a,b){m2=Number(b);$("#m2Slider").slider({value:b});restart()}function updateValue_v1(a,b){v01=Number(b);$("#v1Slider").slider({value:b});restart()}function updateValue_v2(a,b){v02=Number(b);$("#v2Slider").slider({value:b});restart()}
function updateValue_k(a,b){k=Number(b);$("#kSlider").slider({value:b});restart()}
$(function(){$("#m1Slider").slider({range:"min",min:1,max:10,step:1,value:m1,slide:function(a,b){m1=Number(b.value);$("#m1Spinner").spinner().val(b.value);restart()}});$("#m2Slider").slider({range:"min",min:1,max:10,step:1,value:m2,slide:function(a,b){m2=Number(b.value);$("#m2Spinner").spinner().val(b.value);restart()}});$("#v1Slider").slider({range:"min",min:-10,max:10,step:1,value:v01,slide:function(a,b){v01=Number(b.value);$("#v1Spinner").spinner().val(b.value);restart()}});$("#v2Slider").slider({range:"min",
min:-10,max:10,step:1,value:v02,slide:function(a,b){v02=Number(b.value);$("#v2Spinner").spinner().val(b.value);restart()}});$("#eSlider").slider({range:"min",min:0,max:1,step:.01,value:\u03b5,create:function(){$("#texteSlider").text($(this).slider("value").toFixed(1))},slide:function(a,b){\u03b5=Number(b.value.toFixed(1));$("#texteSlider").text(\u03b5);$("#eSlider").slider({value:\u03b5});stage.update()}})});
$(function(){$("#vectorScaleSlider").slider({range:"min",min:0,max:2,step:.01,value:vectorScale,slide:function(a,b){vectorScale=Number(b.value);alignCenter();positions()},stop:function(a,b){vectorScale=Number(b.value);.05>=Math.abs(vectorScale-1)&&(vectorScale=1,$("#vectorScaleSlider").slider({value:vectorScale}));alignCenter();positions()}})});
$(function(){$("#dialog").dialog({autoOpen:!1,closeOnEscape:!0,width:250,resizable:!1,open:function(a,b){$("#kSpinner").blur()},position:{my:"right-5px top+50px",at:"right top",of:demoCanvas}})});