/*!
* © by Sitsanlis Ilias
* This notice shall be included in all copies or substantial portions of the Software.
* Creative Commons 4.0/CC BY - NC - SA 4.0. 
*/

function rnd(a,d){return Math.floor(Math.random()*(d-a+1))+a}function toExp(a){var d=a.toExponential(1),c=d.indexOf("e");a=d.substr(0,c);var e=d.substr(c+2),b="";d=d.substr(c+1,1);for(c=0;c<=e.length-1;c++){var f=e.substr(c,1);if("0"==f)return a;b="1"==f?b+"\u00b9":"2"==f?b+"\u00b2":"3"==f?b+"\u00b3":b+String.fromCharCode("0x207"+f)}return a+"\u00b710"+("-"==d?"\u207b":"")+b}function sngNumber(a){return 0>=a?a.toString():"+"+a.toString()}
function makeDragLine(a,d,c){void 0==a&&(a="#000000");void 0==d&&(d="dragPoint");void 0==c&&(c=100);var e=new createjs.Shape,b=e.graphics;b.setStrokeStyle(2);b.beginStroke(a);b.mt(0,0).lt(0,c);b.endStroke();b.endFill();e.hitArea=new createjs.Shape;e.hitArea.graphics.setStrokeStyle(2);e.hitArea.graphics.beginStroke("#FFFFFF");e.hitArea.graphics.beginFill("#FFFFFF");e.hitArea.graphics.dr(-20,0,40,c);e.hitArea.graphics.endFill();e.hitArea.graphics.endStroke();e.hitArea.alpha=.1;e.name=d;return e}
function makeDragPoint(a,d,c){void 0==a&&(a="#000000");void 0==d&&(d="dragPoint");void 0==c&&(c=5);var e=new createjs.Shape,b=e.graphics;b.setStrokeStyle(1);b.beginStroke(a);b.beginFill(a);b.dc(0,0,c);b.endStroke();b.endFill();e.hitArea=new createjs.Shape;e.hitArea.graphics.beginStroke("#FFFFFF");e.hitArea.graphics.beginFill("#FFFFFF");e.hitArea.graphics.dc(0,0,20);e.hitArea.graphics.endStroke();e.hitArea.alpha=.01;e.name=d;return e}
function makePoint(a,d,c){void 0==a&&(a="#000000");void 0==d&&(d="dragPoint");void 0==c&&(c=5);var e=new createjs.Shape,b=e.graphics;b.setStrokeStyle(1);b.beginStroke(a);b.beginFill(a);b.dc(0,0,c);b.endStroke();b.endFill();e.name=d;return e}
function createVector(a,d,c){void 0==a&&(a="#000000");void 0==d&&(d=!1);void 0==c&&(c=!1);var e=new createjs.Container;new createjs.Shape;var b=createLineVector(a);e.addChild(b);new createjs.Shape;b=createArrowVector(a);e.addChild(b);d&&(new createjs.Shape,d=createDragLineVector(),e.addChild(d));c&&(new createjs.Shape,a=createCircleVector(a),e.addChild(a));return e}
function createLineVector(a){void 0==a&&(a="#000000");var d=new createjs.Shape,c=d.graphics;c.setStrokeStyle(2.5);c.beginStroke(a);c.moveTo(0,0);c.lineTo(100,0);c.endStroke();return d}function createDragLineVector(){var a=new createjs.Shape,d=a.graphics;d.setStrokeStyle(25);d.beginStroke("#ffffff");d.moveTo(0,0);d.lineTo(100,0);d.endStroke();a.alpha=.01;a.name="dragLine";return a}
function createCircleVector(a){a=new createjs.Shape;var d=a.graphics;d.beginFill("#000000");d.dc(0,0,3);a.name="startVector";return a}function createArrowVector(a){void 0==a&&(a="#000000");var d=new createjs.Shape,c=d.graphics;c.setStrokeStyle(1.5,"round","round");c.beginStroke(a);c.beginFill(a);c.moveTo(0,0);c.lineTo(8*Math.cos(155*toRad),-8*Math.sin(155*toRad));c.lineTo(-5.5,0);c.lineTo(8*Math.cos(205*toRad),-8*Math.sin(205*toRad));c.closePath();c.endFill();c.endStroke();return d}
createjs.Container.prototype.setScaleX=function(a){var d=this.getChildAt(0),c=this.getChildAt(1),e=this.getChildByName("dragLine");this.getChildByName("startVector");c.x=a;var b=0>a?-1:1;25<=Math.abs(a)?(c.scaleX=b,d.scaleX=(a-b)/100,null!=e&&(e.scaleX=(a-b)/100)):(c.scaleX=4*a/100,d.scaleX=a/100-4*a/100/100,null!=e&&(e.scaleX=a/100-4*a/100/100))};
function updateTextVector(a,d,c,e){var b=d.rotation;arrowVec=d.getChildAt(1);var f=arrowVec.x;0>f&&(f=Math.abs(f),b+=180);f=Math.abs(f);var g=d.y+f*Math.sin(b*toRad)+c*Math.sin(b*toRad)+e*Math.sin((b+90)*toRad);a.x=d.x+f*Math.cos(b*toRad)+c*Math.cos(b*toRad)+e*Math.cos((b+90)*toRad);a.y=g;a.textBaseline="alphabetic";a.textAlign="center";a.alpha=5>Math.abs(f)?0:1}
function mouseDownVector(a){a.target.offset={x:a.target.x-720/canvas.width*a.stageX,y:a.target.y-420/canvas.height*a.stageY};a.target.addEventListener("pressmove",pressMoveVector)}function pressMoveVector(a){var d=420/canvas.height*a.stageY+a.target.offset.y;a.target.x=720/canvas.width*a.stageX+a.target.offset.x;a.target.y=d;stage.update()}function pressUpVector(a){a.target.removeEventListener("pressmove",pressMoveVector)}
createjs.Shape.prototype.drawDistance=function(a,d,c,e,b,f){void 0==a&&(a="#000000");var g=this.graphics;g.clear();var h=Math.sqrt((e-d)*(e-d)+(b-c)*(b-c));e=Math.atan2(-(b-c),e-d);2<h&&(b=8*(25<h?1:4*h/100),g.setStrokeStyle(1,"round","round"),g.beginStroke(a),g.mt(b*Math.cos(25*toRad),-b*Math.sin(25*toRad)).lt(0,0).lt(b*Math.cos(25*toRad),+b*Math.sin(25*toRad)),g.mt(0,0).lt(h,0).lt(h+b*Math.cos(155*toRad),-b*Math.sin(155*toRad)).mt(h,0).lt(h+b*Math.cos(205*toRad),-b*Math.sin(205*toRad)),g.setStrokeStyle(1),
g.setStrokeDash([2,2],2),g.beginStroke(a),g.mt(0,f/2).lt(0,-f/2),g.mt(h,f/2).lt(h,-f/2),g.endStroke(),g.beginFill("#FFFFFF"),g.dr(h/2-20,-6,40,12),this.rotation=-e*toDeg,this.regX=f*Math.cos(Math.PI/2),this.regY=-f*Math.sin(Math.PI/2),this.x=d,this.y=c)};function fixPeriod(a,d){return a-d*Math.floor(a/d)}var shifted=!1;$(document).on("keyup keydown",function(a){shifted=a.shiftKey});
createjs.Container.prototype.slider=function(a){function d(b){var c=720/canvas.width*b.stageX+b.target.offset.x;0>c&&(c=0);c>a&&(c=a);t=T*(b.target.kT+c/a);calculations();positions()}var c=new createjs.Shape,e=c.graphics;this.addChild(c);e.setStrokeStyle(1);e.beginStroke("#aaa");for(var b=a/12,f=0;12>=f;f++)e.mt(f*b,-2).lt(f*b,-6);e.beginFill("#eee");e.r(0,-2,a,4);e.endFill();c.hitArea=new createjs.Shape;c.hitArea.graphics.beginStroke("#FFFFFF");c.hitArea.graphics.beginFill("#FFFFFF");c.hitArea.graphics.r(0,
-10,a,20);c.hitArea.graphics.endStroke();c.hitArea.alpha=.01;b=new createjs.Shape;this.addChild(b);e=b.graphics;e.setStrokeStyle(1);e.beginStroke("#aaa");e.beginFill("#eee");e.r(-4,-4,8,8);b.hitArea=new createjs.Shape;b.hitArea.graphics.beginStroke("#FFFFFF");b.hitArea.graphics.beginFill("#FFFFFF");b.hitArea.graphics.dc(0,0,20);b.hitArea.graphics.endStroke();b.hitArea.alpha=.01;for(f=0;4>=f;f++){if(0==f)var g=new createjs.Text("0","10px Trebuchet MS","#666666");else 1==f?g=new createjs.Text("T/4",
"10px Trebuchet MS","#666666"):2==f?g=new createjs.Text("T/2","10px Trebuchet MS","#666666"):3==f?g=new createjs.Text("3T/4","10px Trebuchet MS","#666666"):4==f&&(g=new createjs.Text("T","10px Trebuchet MS","#666666"));g.set({textAlign:"center"});g.x=f*a/4;g.y=-18;this.addChild(g)}c.on("click",function(b){if(!isNaN(T)&&isFinite(T)){var c=Math.floor(t/T);t=T*(c+(720/canvas.width*b.stageX-160)/a);b=T/12;var d=t-T*c;.05>=Math.abs(d-b*Math.round(d/b))&&(t=T*c+Math.round(d/b)*b);calculations();positions()}});
b.on("mousedown",function(a){!isNaN(T)&&isFinite(T)&&(a.target.offset={x:a.target.x-720/canvas.width*a.stageX,y:a.target.y-420/canvas.height*a.stageY},a.target.addEventListener("pressmove",d),a.target.kT=Math.floor(t/T))});b.on("pressup",function(b){if(!isNaN(T)&&isFinite(T)){b.target.x==a&&(b.target.x=0);if(!shifted){var c=T/12,e=t-T*b.target.kT;e=Math.abs(e-c*Math.round(e/c));1E-10>Math.abs(t-T*Math.round(t/T))?t=T*Math.round(t/T)+1E-10:e<=c/2&&(t=c*Math.round(t/c))}calculations();positions();b.target.removeEventListener("pressmove",
d)}})};createjs.Shape.prototype.addArrow=function(a,d,c,e){var b=this.graphics;b.ss(1);b.s(a);b.mt(d,c).lt(d+8*Math.cos((155+e)*toRad),c-8*Math.sin((155+e)*toRad)).mt(d,c).lt(d+8*Math.cos((205+e)*toRad),c-8*Math.sin((205+e)*toRad))};