
function F1TextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AAzBBIAAgyIgNAIIAAgIIAKgHQAGgEADgEIADAAIAABBgAg7AcIABgDQAGAAABgBQADgBABgCQACgDADgJIAQg3IACgKIgBgDIgCgCIgHgBIAAgCIBIAAIgHAXIgDAAIABgHQAAgEgDgDQgCgDgEgBIgMAAIgSAAIgLAkIANAAQAIAAADgCQAEgDAEgIIADAAIgKAiIgCAAIABgHQAAgEgDgCQgCgDgIAAIgMAAIgIAbIgCAKQAAABAAAAQAAABAAAAQAAABABAAQAAABABAAQACACAHAAIgBADg");
	
	//shape.regY=-1
	return shape
}

function F2TextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AAaBBIAAgCIAUgfQAHgKAAgHQAAgJgLAAQgDAAgDACIgFAFIgGgFQACgEAEgDQAFgBAGAAQAJAAAGADQAFAEAAAIQAAAIgHALIgPAXIAaAAIAAAIgAhBAcIABgDQAGAAABgBQADgBABgCQACgDADgJIAQg3IACgKIgBgDIgCgCIgHgBIAAgCIBIAAIgHAXIgDAAIABgHQAAgEgDgDQgCgDgEgBIgMAAIgSAAIgLAkIANAAQAIAAAEgCQADgDAEgIIADAAIgJAiIgCAAIABgHQAAgEgDgCQgDgDgIAAIgMAAIgIAbIgCAKQAAABAAAAQAAABAAAAQAAABABAAQAAABABAAQACACAHAAIgBADg");
	//shape.regY=-2
	
	return shape
}

function v1TextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AAnA8IAAgyIgNAIIAAgIIALgHQAGgEADgEIACAAIAABBgAgmAAQgFgDAAgHQAAgEACgJIAGgVIABgFQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAAAgBAAIgDABIgGAHIgCgBQAKgPAJAAQAGAAAAAGIgCAKIgHAYIgCALQAAAFADACQACACAEAAQAJAAAIgLQAHgMAAgPQAAgRgMgCIABgDQATAEAAAUQAAAOgJANQgJAMgPAAQgIAAgFgEg");
	
	shape.regY=-2
	
	return shape
}

function v2TextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AAPA8IAAgCIAVgfQAGgKAAgHQAAgJgKAAQgEAAgDACIgEAEIgGgEQABgEAFgCQAEgDAHAAQAJAAAFAFQAGADAAAIQAAAHgHALIgPAYIAZAAIAAAIgAgtAAQgFgDAAgHQAAgEACgJIAGgVIABgFQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAAAgBAAIgDABIgGAHIgCgBQAKgPAJAAQAGAAAAAGIgCAKIgHAYIgCALQAAAFADACQACACAEAAQAJAAAIgLQAIgMAAgPQAAgRgNgCIABgDQATAEAAAUQAAAOgJANQgJAMgPAAQgIAAgFgEg");
	
	shape.regY=-2
	
	return shape
}

function VTextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AglAvIAIhMIAAgIQAAgDgCgCQgCgCgFAAIgDAAIABgCIAlAAIgBACIgIABQgDABgBADIgBAJIgGA2IAjgwIAIgLIABgEIgCgDQgBgCgFAAIABgCIAcAAIgBACIgFABIgHAGQgEADgIALIg0BGg");
	
	//shape.regY=-1
	return shape
}

function p1TextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AAxA8IAAgyIgNAIIAAgIIAKgHQAGgEADgEIADAAIAABBgAg5AgIABgCQAGAAADgCQACgCACgJIASg7IABgHIgBgDIgDgBIgGAAIAAgCIAYgEIgFAQQAIgJAFgDQAFgEAGAAQAGAAAFAFQAEAFAAAIQAAAPgMAPQgMAPgQAAIgGgBIgGgDIgFASIgBAHIABADIACABIAHABIAAACgAgKgsQgHAIgDALIgGAVQAEAEAHAAQAEAAAEgBQADgCAEgEIAFgJIAFgMQACgHAAgHQAAgFgCgDQgDgDgDAAQgGAAgIAJg");
	
	return shape
}

function p2TextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AAYA8IAAgCIAUgfQAHgKAAgHQAAgJgLAAQgDAAgDACIgFAEIgGgEQACgEAEgCQAFgDAGAAQAJAAAGAFQAFADAAAIQAAAHgHALIgPAYIAaAAIAAAIgAg/AgIABgCQAGAAADgCQACgCACgJIASg7IABgHIgBgDIgDgBIgGAAIAAgCIAYgEIgFAQQAIgJAFgDQAGgEAFAAQAGAAAFAFQAEAFAAAIQAAAPgMAPQgLAPgRAAIgGgBIgGgDIgFASIgBAHIABADIACABIAHABIAAACgAgQgsQgHAIgDALIgGAVQAEAEAHAAQAEAAAEgBQADgCAEgEIAGgJIAEgMQACgHAAgHQAAgFgCgDQgDgDgCAAQgHAAgIAJg");
	
	return shape
}

function pTextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AgzA7IABgDQAHgBADgCQADgCAEgMIAWhLIACgJQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAgBgBIgDgBIgIABIAAgDIAdgFIgFAUQAJgLAIgEQAHgFAHAAQAJAAAFAGQAGAHgBAKQAAATgPASQgQAVgVgBIgGgBIgIgDIgHAXIgBAIIAAAEQABAAAAABQAAAAABAAQAAAAABABQAAAAABAAIAJABIgBADgAAIgoQgIAMgEAOIgIAZQAFAHAJAAQAEAAAFgDQAFgCAEgFQAFgGADgFQAEgHACgIQAEgJAAgJQAAgHgEgDQgDgFgEAAQgJABgKAKg");
	
	return shape
}

function K1TextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AA8BBIAAgyIgNAIIAAgIIALgHQAFgEAEgEIACAAIAABBgAgQAcIABgDQAEAAACgCQABgBAAAAQABAAAAgBQAAAAAAgBQAAgBAAAAIAAgEIgEgHIgTgcIgJAdIgDAKQAAABABAAQAAABAAAAQAAABABAAQAAABABAAQACACAHAAIgBADIglAAIABgDIAHgBIAFgDIADgMIARg3IACgKQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQgBgCgGAAIgBAAIABgCIAiAAIAAACIgHABQgDACAAACIgEALIgIAYIAggZQAGgFACgDIACgDQAAAAAAAAQAAgBAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIAAgCIAeAAIgBACIgIACIgGAEIgOAKIgbAWIAWAiQAGAKAEADQAEACAHAAIgBADg");
	
	return shape
}

function K2TextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AAjBBIAAgCIAUgfQAHgKAAgHQAAgJgKAAQgEAAgDACIgFAFIgFgFQABgEAEgDQAFgBAHAAQAIAAAGADQAFAEABAIQgBAIgHALIgPAXIAaAAIAAAIgAgWAcIABgDQAEAAACgCQABgBAAAAQABAAAAgBQAAAAAAgBQAAgBAAAAIAAgEIgEgHIgTgcIgJAdIgDAKQAAABABAAQAAABAAAAQAAABABAAQAAABABAAQACACAHAAIgBADIglAAIABgDIAHgBIAFgDIADgMIARg3IACgKQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQgBgCgGAAIgBAAIABgCIAiAAIAAACIgHABQgDACgBACIgDALIgIAYIAhgZQAFgFACgDIACgDQAAAAAAAAQAAgBAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIAAgCIAeAAIgBACIgIACIgGAEIgOAKIgbAWIAXAiQAFAKAEADQAEACAHAAIgBADg");
	
	return shape
}

function UTextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AgoAoQgJgIAAgKIABgJIADgKIAJggIACgJQAAgBAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAIgKgCIABgDIAnAAIgBADIgIABQgDABgBADQgCACgDAHIgJAgIgDAMIgBAIQAAAIAGAFQAHAHAKAAQAHgBAFgCQAFgDADgEQAEgFADgIIAFgQIAJgbIADgOQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQgCgCgHAAIABgDIAdAAIAAADIgHABQgDABgCADIgDAJIgKAiQgGARgDAIQgFAIgIAFQgHAFgMABQgOgBgJgHg");
	return shape
}

function ETextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AgzA1IABgDQAFAAADgBQADgBABgCQACgEADgKIATg/IACgMQAAgDgCgCQgCgBgGAAIgCAAIABgDIBLAAIgGAZIgDAAIAAgGQAAgEgCgDQgCgDgGgCQgDgCgOAAIgNAAIgLArIAJAAQAKAAAFgEQAFgDADgJIAEAAIgMAmIgDAAIABgIIgBgGIgDgDIgKgBIgKAAIgKAjIgCAIQAAABABAAQAAABAAAAQAAABABAAQAAAAAAABQACABAFAAIAJAAQAPAAAJgGQAJgFAIgNIACAAIgJAdg");
	return shape
}

function cmTextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AhVAcQgJgLAAgRQAAgQAKgLQAKgKAOAAQALAAAHAGQAHAFAAAGQAAADgCACQgCACgEAAQgEAAgDgDIgBgGQgBgFgDgDQgCgCgFAAQgIAAgFAGQgGAHAAAOQAAALAGAKQAHAKAKAAQAIAAAGgFQAEgEAEgKIADABQgDAPgJAIQgIAHgKAAQgNAAgJgKgAA7AkIAAgDIACAAQAFAAACgBIADgFIAAgHIAAgeQAAgJgCgDQgDgGgHAAQgEAAgEACQgEADgGAFIgBABIABAEIAAAhIAAAJIAEADIAHABIAAADIgkAAIAAgDIAIgBQACgBABgEIABgHIAAgeQAAgJgDgEQgDgFgHAAQgEAAgEACQgGAEgDAEIAAAmQAAAHABACIACADQACABAGAAIAAADIgjAAIAAgDIAHgBIADgDIABgJIAAgaQAAgMgBgEIgBgEIgDgBIgGABIgBgDIAWgIIADAAIAAAQIAIgKQAEgDAEgCIAIgBQAHAAAFAEQAEAEACAIQAIgKAGgDQAFgDAGAAQAGAAAEADQAFADACAHQACAEAAAKIAAAeIABAJIADADIAHABIAAADg");
	
	shape.scale = 0.8
	
	return shape
}

function vcmTextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AgSAjQgGgGAAgMQAAgLAHgGQAGgGAJAAQAGAAAFADQAEADAAAEIgBADIgDABQgBAAgBAAQgBAAAAAAQgBgBAAAAQgBAAAAgBIgBgEQAAgBgBAAQAAgBAAAAQAAAAgBAAQAAgBAAAAQgBgCgEAAQgFAAgDADQgDAFAAAIQAAAIADAHQAFAGAGAAQAFAAADgDIAGgJIABABQgCAJgFAFQgGAFgFAAQgIAAgGgHgABLApIAAgCIABAAIAFgBIACgDIAAgFIAAgUIgBgIQgCgCgFAAQgDAAgDAAIgGAFIAAAZIABAGIACACIAEABIAAACIgXAAIAAgCIAFgBIADgDIAAgFIAAgUQAAgGgCgCQgCgCgEAAIgGAAQgEACgDADIAAAZQAAAFACABIABACIAFABIAAACIgXAAIAAgCIAEgBIACgCIABgGIAAgSIgBgKIgBgCIgCAAIgDAAIAAgBIANgFIACAAIAAAJIAGgFIAGgDIAFgBQAEAAADACQADADACAEQAFgGAEgBQADgCAEAAQADAAADACQADABACAEIABAJIAAAUIABAGIABACIAFABIAAACgAhWAaQgGgFAAgHQAAgFADgJIAGgYIABgGQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABAAAAIgIAIIgCgBQALgRALAAQAHAAAAAHIgCALIgIAbQgDAHAAAFQAAAGAEACQADADADAAQAKAAAKgNQAJgOAAgRQAAgTgPgCIABgDQAXAEAAAXQAAAPgLAPQgLAPgQAAQgKAAgFgFg");
	
	shape.scale = 0.8
	
	return shape
}

