/*!
* © by Sitsanlis Ilias
* This notice shall be included in all copies or substantial portions of the Software.
*/

helpText.text = "Με την συγκεκριμένη προσομοίωση μπορείς να μελετήσεις την ελαστική κρούση δυο σφαιρών. Μπορείς να μετακινήσεις τις σφαίρες και να περιστρέψεις τα διανύσματα των ταχυτήτων τους ώστε να καθορίσεις την διεύθυνση και το μέτρο της ταχύτητας κάθε σφαίρας."

var canvas,stage,self,percent=.79,marginVarNumber=200,marginVar=marginVarNumber,controlBoxContainer,PI=Math.PI,toDeg=180/PI,toRad=PI/180,X0=180,Y0=197,Xg=540,Yg=197,Xga=620,Yga=197,t=0,dt=1/60,\u03b4=.001,dtInitial=dt,dtSlow=dt,factor=.5,playMovie=!1,framePlay=!1,xScale=50,yScale=-xScale,vScale=8,pScale=5,energyScale=4,vectorsScale=1,valuesText=new createjs.Text("","12px Trebuchet MS");valuesText.set({x:360,y:375});valuesText.set({textAlign:"center"});
var ds1=String.fromCharCode("0x2081"),ds2=String.fromCharCode("0x2082"),moires=String.fromCharCode(186),m1=2,m2=2,x01=-1.5,x02=1.5,y01=.25,y02=0,x1,x2,y1,y2,xcm,ycm,v01x=5,v01y=0,v01=Math.sqrt(v01x*v01x+v01y*v01y),\u03b801=Math.atan2(v01y,v01x),v02x=0,v02y=0,v02=Math.sqrt(v02x*v02x+v02y*v02y),\u03b802=Math.atan2(v02y,v02x),v1x,v1y,v1,\u03b81,v2x,v2y,v2,\u03b82,Xmax=340,Xmin=20,Ymax=37,Ymin=357,xMax=(Xmax-X0)/xScale,xMin=(Xmin-X0)/xScale,yMax=(Ymax-Y0)/yScale,yMin=(Ymin-Y0)/yScale,\u03b5=1,body1=new createjs.Shape;
body1.name="body1";body1.addEventListener("mousedown",mouseDownGen);body1.addEventListener("pressup",pressUpGen);body1.mouseChildren=!1;var body2=new createjs.Shape;body2.name="body2";body2.addEventListener("mousedown",mouseDownGen);body2.addEventListener("pressup",pressUpGen);body2.mouseChildren=!1;var v1Vec=createVector("#FF0000",!0,!1);v1Vec.y=Y0-40;v1Vec.addEventListener("mousedown",mouseDownVector);v1Vec.addEventListener("pressup",pressUpVector);v1Vec.mouseChildren=!1;v1Vec.name="v1Vec";
var v1Text=v1TextCreate(),v2Vec=createVector("#0000FF",!0,!1);v2Vec.y=Y0-45;v2Vec.addEventListener("mousedown",mouseDownVector);v2Vec.addEventListener("pressup",pressUpVector);v2Vec.mouseChildren=!1;v2Vec.name="v2Vec";var v2Text=v2TextCreate(),p1Vec=createVector("#990000",!1,!1);p1Vec.set({x:Xg,y:Yg});var p1Text=p1TextCreate(),p2Vec=createVector("#990099",!1,!1);p2Vec.set({x:Xg,y:Yg});var p2Text=p2TextCreate(),pVec=createVector("#009900",!1,!1);pVec.set({x:Xg,y:Yg});
var pText=pTextCreate(),dotLines=new createjs.Shape;dotLines.set({x:Xg,y:Yg});var pVecContainer=new createjs.Container,helpLines=new createjs.Shape,box=new createjs.Shape,cm=makePoint("#666666","cm",1.5);cm.visible=!1;var path1=new createjs.Shape,path2=new createjs.Shape,cmPath=new createjs.Shape,isDraggin=!1;pVecContainer.visible=!0;
function init(){stage=new createjs.Stage(document.getElementById("demoCanvas"));createjs.Touch.enable(stage);stage.enableMouseOver();canvas=document.getElementById("demoCanvas");self=stage;controlBoxContainer=new createjs.Container;self.addChild(controlBoxContainer);var a=new createjs.DOMElement("foo");controlBoxContainer.addChild(a);controlBoxContainer.x=5;controlBoxContainer.y=3.5;controlBoxContainer.alpha=.9;stage.addChild(valuesText);box.graphics.clear().ss(1).s("#666").dr(Xmin,Ymax,Xmax-Xmin,
Ymin-Ymax).mt(380,Ymax).dr(380,Ymax,320,Ymin-Ymax).s("#990099").mt(Xg,Yg).f("#990099").dc(Xg,Yg,3);pVecContainer.addChild(dotLines);stage.addChild(path1);stage.addChild(path2);stage.addChild(cmPath);stage.addChild(body1);stage.addChild(body2);stage.addChild(v1Vec);stage.addChild(v2Vec);stage.addChild(v1Text);stage.addChild(v2Text);stage.addChild(helpLines);pVecContainer.addChild(p1Vec);pVecContainer.addChild(p2Vec);pVecContainer.addChild(pVec);stage.addChild(pVecContainer);pVecContainer.addChild(p1Text);
pVecContainer.addChild(p2Text);pVecContainer.addChild(pText);stage.addChild(box);stage.addChild(cm);createRegister();stage.addChild(\u03a8);addFunction();showHideVariables();handleComplete();initialize();createjs.Ticker.timingMode=createjs.Ticker.RAF;createjs.Ticker.addEventListener("tick",tick);canvas.style.visibility="visible";document.getElementById("variables").style.visibility="visible"}function initialize(){restart()}
function restart(){isOk||stage.removeAllChildren();x1=x01;x2=x02;y1=y01;y2=y02;v1x=v01x;v1y=v01y;v2x=v02x;v2y=v02y;v1=v01;\u03b81=\u03b801;v2=v02;\u03b82=\u03b802;R1=.25*Math.sqrt(m1);R2=.25*Math.sqrt(m2);1.7<R1&&(R1=1.7);.1>R1&&(R1=.1);1.7<R2&&(R2=1.7);.1>R2&&(R2=.1);body1.graphics.clear().ss(1).s("#666666").f("#FF9933").dc(0,0,R1*xScale);body2.graphics.clear().ss(1).s("#666666").f("#8C99F7").dc(0,0,R2*xScale);path1.graphics.clear().ss(2).s("#FF9933").mt(X0+x1*xScale,Y0+y1*yScale);path2.graphics.clear().ss(2).s("#8C99F7").mt(X0+
x2*xScale,Y0+y2*yScale);cmPath.graphics.clear().ss(2).s("#666666").mt(X0+(m1*x1+m2*x2)*xScale/(m1+m2),Y0+(m1*y1+m2*y2)*yScale/(m1+m2));positions()}function tick(a){playMovie&&(framePlay&&(framePlay=playMovie=!1),positionsAfterCollition(),positions())}
function positions(){body1.x=v1Vec.x=X0+x1*xScale;body1.y=v1Vec.y=Y0+y1*yScale;body2.x=v2Vec.x=X0+x2*xScale;body2.y=v2Vec.y=Y0+y2*yScale;v1=Math.sqrt(v1x*v1x+v1y*v1y);v2=Math.sqrt(v2x*v2x+v2y*v2y);\u03b81=Math.atan2(v1y,v1x);\u03b82=Math.atan2(v2y,v2x);var a=.98<Math.abs(Math.cos(\u03b82-\u03b81))?!0:!1;v1Vec.setScaleX(v1*vScale*vectorsScale);v1Vec.rotation=-\u03b81*toDeg;updateTextVector(v1Text,v1Vec,12,0);v2Vec.setScaleX(v2*vScale*vectorsScale);v2Vec.rotation=-\u03b82*toDeg;updateTextVector(v2Text,
v2Vec,12,0);p1Vec.norm=m1*v1;p1Vec.setScaleX(m1*v1*pScale*vectorsScale);p1Vec.rotation=-\u03b81*toDeg;updateTextVector(p1Text,p1Vec,1==a?5:15,1==a?15:0);p2Vec.norm=m2*v2;p2Vec.setScaleX(m2*v2*pScale*vectorsScale);p2Vec.rotation=-\u03b82*toDeg;updateTextVector(p2Text,p2Vec,1==a?5:15,1==a?15:0);var b=m1*v1x+m2*v2x,c=m1*v1y+m2*v2y,d=Math.sqrt(b*b+c*c);pVec.norm=d;pVec.setScaleX(d*pScale*vectorsScale);pVec.rotation=-Math.atan2(c,b)*toDeg;updateTextVector(pText,pVec,1==a?5:15,1==a?-15:0);dotLines.graphics.clear().ss(1).sd([2,
2],2).s("#000").mt(m1*v1x*pScale*vectorsScale,-m1*v1y*pScale*vectorsScale).lt(m1*v1x*pScale*vectorsScale+m2*v2x*pScale*vectorsScale,-m1*v1y*pScale*vectorsScale-m2*v2y*pScale*vectorsScale).lt(m2*v2x*pScale*vectorsScale,-m2*v2y*pScale*vectorsScale);arangeVectorsInContainer(pVecContainer);cm.x=X0+xScale*(m1*x1+m2*x2)/(m1+m2);cm.y=Y0+yScale*(m1*y1+m2*y2)/(m1+m2);$("#path").is(":checked")&&!isDraggin&&(path1.graphics.lt(X0+x1*xScale,Y0+y1*yScale),path2.graphics.lt(X0+x2*xScale,Y0+y2*yScale),$("#cm").is(":checked")&&
!isDraggin&&cmPath.graphics.lt(cm.x,cm.y));valuesText.text="V"+ds1+" = "+v1.toFixed(1)+" m/s, \u03b8"+ds1+" = "+(\u03b81*toDeg).toFixed(0)+moires+", V"+ds2+" = "+v2.toFixed(1)+" m/s, \u03b8"+ds2+" = "+(\u03b82*toDeg).toFixed(0)+moires;stage.update()}
function positionsAfterCollition(){var a=x2-x1,b=y2-y1,c=v2x-v1x,d=v2y-v1y,f=a*c+b*d;c=c*c+d*d;b=Math.sqrt(f*f-c*(a*a+b*b-(R1+R2)*(R1+R2)));a=(-f-b)/c;f=(-f+b)/c;f=0<dt?Math.min(a,f):Math.max(a,f);a=[];0<v1x*dt?a.push((xMax-R1-x1)/v1x):0>v1x*dt?a.push((xMin+R1-x1)/v1x):a.push(NaN);0<v1y*dt?a.push((yMax-R1-y1)/v1y):0>v1y*dt?a.push((yMin+R1-y1)/v1y):a.push(NaN);0<v2x*dt?a.push((xMax-R2-x2)/v2x):0>v2x*dt?a.push((xMin+R2-x2)/v2x):a.push(NaN);0<v2y*dt?a.push((yMax-R2-y2)/v2y):0>v2y*dt?a.push((yMin+R2-
y2)/v2y):a.push(NaN);b=999999999999;c=-999999999999;for(d=0;3>=d;d++){if(a[d]<=b){var e=d;b=a[d]}if(a[d]>=c){var g=d;c=a[d]}}e=0<dt?e:g;tB=a[e];!isNaN(tB)&&Math.abs(tB)<=Math.abs(dt)?(x1+=v1x*tB,y1+=v1y*tB,x2+=v2x*tB,y2+=v2y*tB,0==e&&(v1x=-v1x),1==e&&(v1y=-v1y),2==e&&(v2x=-v2x),3==e&&(v2y=-v2y),t+=tB):Math.abs(f)<=Math.abs(dt)&&!isNaN(f)&&willCollide()?(x1+=v1x*f,y1+=v1y*f,x2+=v2x*f,y2+=v2y*f,e=Math.atan2(y2-y1,x2-x1),g=v1x*Math.cos(e)+v1y*Math.sin(e),a=v1y*Math.cos(e)-v1x*Math.sin(e),b=v2x*Math.cos(e)+
v2y*Math.sin(e),c=v2y*Math.cos(e)-v2x*Math.sin(e),d=((1+\u03b5)*m1*g+(m2-\u03b5*m1)*b)/(m1+m2),g=((m1-\u03b5*m2)*g+m2*(1+\u03b5)*b)/(m1+m2),b=d,v2x=b*Math.cos(e)-c*Math.sin(e),v2y=b*Math.sin(e)+c*Math.cos(e),v1x=g*Math.cos(e)-a*Math.sin(e),v1y=g*Math.sin(e)+a*Math.cos(e),t+=f):(x1+=v1x*dt,y1+=v1y*dt,x2+=v2x*dt,y2+=v2y*dt,t+=dt)}function willCollide(){var a=!1,b=x1+v1x*dt,c=y1+v1y*dt,d=x2+v2x*dt,f=y2+v2y*dt;Math.sqrt((d-b)*(d-b)+(f-c)*(f-c))<=R1+R2&&(a=!0);return a}
function arangeVectorsInContainer(a){a.sortChildren(function(a,c){return Math.abs(a.norm)>Math.abs(c.norm)?-1:Math.abs(a.norm)<Math.abs(c.norm)?1:0})}function ArangeOverlayWithWall(a,b){var c=(X0-a.x)/xScale,d=(Y0-a.y)/yScale;c>xMax-b&&(c=xMax-b);c<xMin+b&&(c=xMin+b);d>yMax-b&&(d=yMax-b);d<yMin+b&&(d=yMin+b);a.x=X0+c*xScale;a.y=Y0+d*yScale};
