/*!
* © by Sitsanlis Ilias
* This notice shall be included in all copies or substantial portions of the Software.
*/

function sng(a){return 0>=a?a.toString():"+"+a.toString()}
function makeDragLine(a,e,c){void 0==a&&(a="#000000");void 0==e&&(e="dragPoint");void 0==c&&(c=100);var b=new createjs.Shape,d=b.graphics;d.setStrokeStyle(2);d.beginStroke(a);d.mt(0,0).lt(0,c);d.endStroke();d.endFill();b.hitArea=new createjs.Shape;b.hitArea.graphics.setStrokeStyle(2);b.hitArea.graphics.beginStroke("#FFFFFF");b.hitArea.graphics.beginFill("#FFFFFF");b.hitArea.graphics.dr(-20,0,40,c);b.hitArea.graphics.endFill();b.hitArea.graphics.endStroke();b.hitArea.alpha=.1;b.name=e;return b}
function makeDragPoint(a,e,c){void 0==a&&(a="#000000");void 0==e&&(e="dragPoint");void 0==c&&(c=5);var b=new createjs.Shape,d=b.graphics;d.setStrokeStyle(1);d.beginStroke(a);d.beginFill(a);d.dc(0,0,c);d.endStroke();d.endFill();b.hitArea=new createjs.Shape;b.hitArea.graphics.beginStroke("#FFFFFF");b.hitArea.graphics.beginFill("#FFFFFF");b.hitArea.graphics.dc(0,0,20);b.hitArea.graphics.endStroke();b.hitArea.alpha=.01;b.name=e;return b}
function makePoint(a,e,c){void 0==a&&(a="#000000");void 0==e&&(e="dragPoint");void 0==c&&(c=5);var b=new createjs.Shape,d=b.graphics;d.setStrokeStyle(1);d.beginStroke(a);d.beginFill(a);d.dc(0,0,c);d.endStroke();d.endFill();b.name=e;return b}
function createVector(a,e,c){void 0==a&&(a="#000000");void 0==e&&(e=!1);void 0==c&&(c=!1);var b=new createjs.Container;new createjs.Shape;var d=createLineVector(a);b.addChild(d);new createjs.Shape;d=createArrowVector(a);b.addChild(d);e&&(new createjs.Shape,e=createDragLineVector(),b.addChild(e));c&&(new createjs.Shape,a=createCircleVector(a),b.addChild(a));return b}
function createLineVector(a){void 0==a&&(a="#000000");var e=new createjs.Shape,c=e.graphics;c.setStrokeStyle(2.5);c.beginStroke(a);c.moveTo(0,0);c.lineTo(100,0);c.endStroke();return e}function createDragLineVector(){var a=new createjs.Shape,e=a.graphics;e.setStrokeStyle(15);e.beginStroke("#ffffff");e.moveTo(0,0);e.lineTo(100,0);e.endStroke();a.alpha=.01;a.name="dragLine";return a}
function createCircleVector(a){a=new createjs.Shape;var e=a.graphics;e.beginFill("#000000");e.dc(0,0,3);a.name="startVector";return a}function createArrowVector(a){void 0==a&&(a="#000000");var e=new createjs.Shape,c=e.graphics;c.setStrokeStyle(1.5,"round","round");c.beginStroke(a);c.beginFill(a);c.moveTo(0,0);c.lineTo(8*Math.cos(155*toRad),-8*Math.sin(155*toRad));c.lineTo(-5.5,0);c.lineTo(8*Math.cos(205*toRad),-8*Math.sin(205*toRad));c.closePath();c.endFill();c.endStroke();return e}
createjs.Container.prototype.setScaleX=function(a){var e=this.getChildAt(0),c=this.getChildAt(1),b=this.getChildByName("dragLine");this.getChildByName("startVector");c.x=a;var d=0>a?-1:1;25<=Math.abs(a)?(c.scaleX=d,e.scaleX=(a-d)/100,null!=b&&(b.scaleX=(a-d)/100)):(c.scaleX=4*a/100,e.scaleX=a/100-4*a/100/100,null!=b&&(b.scaleX=a/100-4*a/100/100))};
function updateTextVector(a,e,c,b){var d=e.rotation;arrowVec=e.getChildAt(1);var f=arrowVec.x;0>f&&(f=Math.abs(f),d+=180);f=Math.abs(f);var g=Math.sqrt(c*c+b*b);c=Math.atan2(b,c);b=e.y+f*Math.sin(d*toRad)-g*Math.sin(-d*toRad+c);a.x=e.x+f*Math.cos(d*toRad)+g*Math.cos(-d*toRad+c);a.y=b;a.textBaseline="alphabetic";a.textAlign="center";a.alpha=5>Math.abs(f)?0:1}function mouseDownVector(a){a.target.addEventListener("pressmove",pressMoveVector)}
function pressMoveVector(a){var e=720/canvas.width*a.stageX-a.target.x,c=420/canvas.height*a.stageY-a.target.y,b=Math.atan2(-c,e);e=Math.sqrt(e*e+c*c);helpLines.graphics.clear();"v1Vec"==a.target.name?(v1=e/(vScale*vectorsScale),\u03b81=b,a=Math.atan2(y2-y1,x2-x1),2>Math.abs((a-\u03b81)*toDeg)&&(helpLines.graphics.ss(1).sd([2,2],2).s("#666").mt(body1.x,body1.y).lt(body2.x,body2.y),\u03b81=b=a),v1x=v1*Math.cos(b),v1y=v1*Math.sin(b)):"v2Vec"==a.target.name&&(v2=e/(vScale*vectorsScale),\u03b82=b,a=Math.atan2(y1-
y2,x1-x2),2>Math.abs((a-\u03b82)*toDeg)&&(helpLines.graphics.ss(1).sd([2,2],2).s("#666").mt(body1.x,body1.y).lt(body2.x,body2.y),\u03b82=b=a),v2x=v2*Math.cos(b),v2y=v2*Math.sin(b));updateInitialValuesVelocityAfterUpdate();restart()}function pressUpVector(a){helpLines.graphics.clear();a.target.removeEventListener("pressmove",pressMoveVector);stage.update()}
function updateInitialValuesVelocityAfterUpdate(){v01x=v1x;v01y=v1y;v01=v1;\u03b801=\u03b81;v02x=v2x;v02y=v2y;v02=v2;\u03b802=\u03b82;updateSpinnerAndSliders()}
createjs.Shape.prototype.drawDistance=function(a,e,c,b,d,f){void 0==a&&(a="#000000");var g=this.graphics;g.clear();var h=Math.sqrt((b-e)*(b-e)+(d-c)*(d-c));b=Math.atan2(-(d-c),b-e);2<h&&(d=8*(25<h?1:4*h/100),g.setStrokeStyle(1,"round","round"),g.beginStroke(a),g.mt(d*Math.cos(25*toRad),-d*Math.sin(25*toRad)).lt(0,0).lt(d*Math.cos(25*toRad),+d*Math.sin(25*toRad)),g.mt(0,0).lt(h,0).lt(h+d*Math.cos(155*toRad),-d*Math.sin(155*toRad)).mt(h,0).lt(h+d*Math.cos(205*toRad),-d*Math.sin(205*toRad)),g.setStrokeStyle(1),
g.setStrokeDash([2,2],2),g.beginStroke(a),g.mt(0,f/2).lt(0,-f/2),g.mt(h,f/2).lt(h,-f/2),g.endStroke(),g.beginFill("#FFFFFF"),g.dr(h/2-20,-6,40,12),this.rotation=-b*toDeg,this.regX=f*Math.cos(Math.PI/2),this.regY=-f*Math.sin(Math.PI/2),this.x=e,this.y=c)};function fixPeriod(a,e){return a-e*Math.floor(a/e)}var shifted=!1;$(document).on("keyup keydown",function(a){shifted=a.shiftKey});
createjs.Container.prototype.slider=function(a){function e(b){var c=720/canvas.width*b.stageX+b.target.offset.x;0>c&&(c=0);c>a&&(c=a);t=T*(b.target.kT+c/a);calculations();positions()}var c=new createjs.Shape,b=c.graphics;this.addChild(c);b.setStrokeStyle(1);b.beginStroke("#aaa");for(var d=a/12,f=0;12>=f;f++)b.mt(f*d,-2).lt(f*d,-6);b.beginFill("#eee");b.r(0,-2,a,4);b.endFill();c.hitArea=new createjs.Shape;c.hitArea.graphics.beginStroke("#FFFFFF");c.hitArea.graphics.beginFill("#FFFFFF");c.hitArea.graphics.r(0,
-10,a,20);c.hitArea.graphics.endStroke();c.hitArea.alpha=.01;d=new createjs.Shape;this.addChild(d);b=d.graphics;b.setStrokeStyle(1);b.beginStroke("#aaa");b.beginFill("#eee");b.r(-4,-4,8,8);d.hitArea=new createjs.Shape;d.hitArea.graphics.beginStroke("#FFFFFF");d.hitArea.graphics.beginFill("#FFFFFF");d.hitArea.graphics.dc(0,0,20);d.hitArea.graphics.endStroke();d.hitArea.alpha=.01;for(f=0;4>=f;f++){if(0==f)var g=new createjs.Text("0","10px Trebuchet MS","#666666");else 1==f?g=new createjs.Text("T/4",
"10px Trebuchet MS","#666666"):2==f?g=new createjs.Text("T/2","10px Trebuchet MS","#666666"):3==f?g=new createjs.Text("3T/4","10px Trebuchet MS","#666666"):4==f&&(g=new createjs.Text("T","10px Trebuchet MS","#666666"));g.set({textAlign:"center"});g.x=f*a/4;g.y=-18;this.addChild(g)}c.on("click",function(b){if(!isNaN(T)&&isFinite(T)){var c=Math.floor(t/T);t=T*(c+(720/canvas.width*b.stageX-160)/a);b=T/12;var d=t-T*c;.05>=Math.abs(d-b*Math.round(d/b))&&(t=T*c+Math.round(d/b)*b);calculations();positions()}});
d.on("mousedown",function(a){!isNaN(T)&&isFinite(T)&&(a.target.offset={x:a.target.x-720/canvas.width*a.stageX,y:a.target.y-420/canvas.height*a.stageY},a.target.addEventListener("pressmove",e),a.target.kT=Math.floor(t/T))});d.on("pressup",function(b){if(!isNaN(T)&&isFinite(T)){b.target.x==a&&(b.target.x=0);if(!shifted){var c=T/12,d=t-T*b.target.kT;d=Math.abs(d-c*Math.round(d/c));1E-10>Math.abs(t-T*Math.round(t/T))?t=T*Math.round(t/T)+1E-10:d<=c/2&&(t=c*Math.round(t/c))}calculations();positions();b.target.removeEventListener("pressmove",
e)}})};