function v1TextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AArBFIAAg5IgQAKIAAgKIANgIQAGgEAEgEIADAAIAABJgAgoAHQgGgFAAgHQAAgGADgLIAHgbIACgHQAAAAAAgBQgBAAAAgBQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAABIgIAJIgDgCQANgTAMAAQAIAAAAAIQAAAEgDAIIgJAfQgDAJAAAFQAAAFAEADQADAEAFAAQALAAAKgPQAKgPAAgUQAAgVgPgDIAAgDQAZAEAAAbQAAARgMARQgLAPgTAAQgLAAgGgFg");
	
	shape.regY = -2;
	return shape;
}

function v2TextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AAMBIIAAgCIAYgkQAHgLAAgIQAAgKgMAAQgEAAgDACQgEACgBADIgHgFQABgFAGgCQAFgDAHAAQALAAAFAEQAHAFAAAJQAAAIgIANIgRAbIAdAAIAAAJgAgtAFQgGgFgBgIQAAgFADgMIAIgaIABgHQAAgBAAAAQAAgBAAAAQgBAAAAgBQgBAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAAAQgBABAAAAIgIAJIgDgCQAMgTAMAAQAJAAgBAIQABAEgDAIIgJAgQgDAIAAAFQAAAGAEADQADADAFAAQALAAAKgOQAJgQAAgTQAAgWgOgCIAAgEQAZAFAAAaQAAASgNAQQgKAQgTAAQgLAAgGgFg");
	
	shape.regY = -2;
	return shape;
}

function pTextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AgzA7IABgDQAHgBADgCQADgCAEgMIAWhLIACgJQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAgBgBIgDgBIgIABIAAgDIAdgFIgFAUQAJgLAIgEQAHgFAHAAQAJAAAFAGQAGAHgBAKQAAATgPASQgQAVgVgBIgGgBIgIgDIgHAXIgBAIIAAAEQABAAAAABQAAAAABAAQAAAAABABQAAAAABAAIAJABIgBADgAAIgoQgIAMgEAOIgIAZQAFAHAJAAQAEAAAFgDQAFgCAEgFQAFgGADgFQAEgHACgIQAEgJAAgJQAAgHgEgDQgDgFgEAAQgJABgKAKg");
	
	//shape.regY = -2;
	return shape;
}

function paTextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AhZA7IABgDQAIgBADgCQADgCADgMIAXhLIACgJQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBIgEgBIgHABIAAgDIAegFIgGAUQAKgLAHgEQAIgFAHAAQAHAAAGAGQAFAHAAAKQAAATgPASQgPAVgVgBIgIgBIgHgDIgHAXIgCAIIABAEQABAAAAABQAAAAABAAQAAAAABABQAAAAABAAIAJABIgBADgAgcgoQgJAMgFAOIgHAZQAFAHAJAAQAFAAAFgDQAEgCAFgFQAEgGAEgFQAEgHACgIQACgJAAgJQAAgHgCgDQgDgFgEAAQgKABgJAKgABCgVIAIgXIAQAAIgNAXg");
	
	shape.regY = -2;
	return shape;
}

function p1TextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AA8BTIAAg1IgPAJIAAgNQAPgHAIgKIAFAAIAABKgAhIAjIABgEQAIAAADgCQADgDADgLIAWhMIACgJQAAAAAAgBQAAAAAAgBQAAAAgBgBQAAAAAAgBIgEgBIgIABIAAgEIAfgEIgGAUQAJgLAIgFQAGgEAIAAQAIAAAFAGQAGAGAAAKQAAATgQAUQgQAUgUAAIgHgBIgIgDIgGAWIgCAIIABAEQAAAAAAAAQABABAAAAQABAAAAAAQABABAAAAIAJAAIgBAEgAgMhAQgJALgEAPIgIAaQAGAHAJAAQAEAAAFgDQAFgDAEgFQAEgFADgGQAEgHADgJQADgIAAgJQAAgHgDgEQgEgEgEAAQgIAAgKALg");
	
	shape.regX = -1.8;
	shape.regY = -2;
	return shape;
}

function p2TextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AAgBTIAAgEIAYgiQAGgLAAgHQAAgIgKAAQgHAAgFAIIgJgHQADgFAGgEQAFgDAHAAQALAAAHAFQAGAFAAAJQAAAJgIAMIgQAYIAcAAIAAALgAhPAjIABgEQAHAAAEgCQACgDAEgLIAWhMIACgJQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAgBgBIgDgBIgIABIAAgEIAegEIgFAUQAJgLAHgFQAIgEAGAAQAJAAAFAGQAGAGgBAKQAAATgPAUQgPAUgVAAIgHgBIgIgDIgHAWIgBAIIABAEQAAAAAAAAQAAABABAAQAAAAABAAQAAABABAAIAJAAIgBAEgAgThAQgJALgEAPIgIAaQAGAHAJAAQAEAAAFgDQAEgDAFgFQAEgFADgGQAEgHACgJQADgIABgJQgBgHgDgEQgDgEgDAAQgKAAgJALg");
	
	shape.regX = -2.5;
	shape.regY = -2;
	return shape;
}

function p1aTextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AAaBbIAAg1IgPAIIAAgMQAOgIAJgJIAFAAIAABKgAhZAbIABgEQAIAAADgCQADgDADgKIAXhNIACgJQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAgBAAIgEgBIgHAAIAAgEIAegEIgGAUQAKgLAHgFQAIgEAHAAQAHAAAGAGQAFAGAAAKQAAAUgPAUQgPATgVABIgIgBIgHgEIgHAWIgCAJIABADQABAAAAABQAAAAABAAQAAABABAAQAAAAABAAIAJAAIgBAEgAgchHQgJALgFAOIgHAbQAFAGAJAAQAFAAAFgDQAEgDAFgFQAEgEAEgHQAEgGACgKQACgIAAgJQAAgHgCgDQgDgEgEAAQgKAAgJALgABCg0IAIgZIAQAAIgNAZg");
	
	shape.regY = -2;
	return shape;
}

function p2aTextCreate() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AAFBbIAAgEIAXgiQAHgLAAgHQAAgIgKAAQgIAAgEAIIgJgHQACgFAGgEQAGgDAHAAQALAAAHAFQAGAFAAAJQAAAJgIAMIgQAYIAcAAIAAALgAhZAbIABgEQAIAAADgCQADgDADgLIAXhMIACgJQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBIgEgBIgHABIAAgEIAegEIgGAUQAKgLAHgFQAIgEAHAAQAHAAAGAGQAFAGAAAKQAAATgPAUQgPAUgVAAIgIgBIgHgDIgHAWIgCAIIABAEQABAAAAAAQAAABABAAQAAAAABAAQAAABABAAIAJAAIgBAEgAgchIQgJALgFAPIgHAaQAFAHAJAAQAFAAAFgDQAEgDAFgFQAEgFAEgGQAEgHACgJQACgIAAgJQAAgHgCgEQgDgEgEAAQgKAAgJALgABCg1IAIgYIAQAAIgNAYg");
	
	shape.regY = -2;
	return shape;
}