/*!
* © by Sitsanlis Ilias
* This notice shall be included in all copies or substantial portions of the Software.
* Creative Commons 4.0/CC BY - NC - SA 4.0. 
*/

helpText.text = "Εφαρμογή με την οποία μπορούμε να μελετήσουμε την έννοια αδράνεια ενός σώματος. Αν κάνουμε κλικ σε κάποιο σημείο στην οθόνη και σύρουμε τότε στο σώμα (Η κουκίδα αναπαριστά ένα σώμα - υλικό σημείο) εφαρμόζεται δύναμη η οποία είναι ανάλογη της απόστασης του σωμάτος από τον δείκτη του ποντικιού. Αν η μάζα του σώματος είναι μεγάλη (μεγάλη αδράνεια) το σώμα είναι δυσκίνητο ξεκινάει δύσκολα, στρίβει δύσκολα και σταματάει δύσκολα. Στο σώμα ενεργεί δύναμη τριβής που είναι ανάλογη της ταχύτητας (b η σταθερά απόσβεσης). Αν καταργήσουμε την δύναμη και δεν υπάρχει τριβή τότε το σώμα συνεχίζει να κινείται ευθύγραμμα και ομαλά. Αν να πατήσετε το πλήκτρο SPACE κατα την διάρκεια της κίνησης τότε σταματά προσωρινά η προσομοίωση. Αν τώρα πατήσετε το πλήκτρο SHIFT σχεδιάζεται η ακτίνα καμπυλότητας και το κέντρο της κυκλικής τροχιάς, τοποθετώντας τον δείκτη του ποντικιού στο κέντρο όταν δεν υπάρχει τριβή θα έχουμε μια ομαλή κυκλική κίνηση."

var canvas,stage,self,marginVarNumber=91,marginVar=marginVarNumber,controlBoxContainer,PI=Math.PI,toDeg=180/PI,toRad=PI/180,moires=String.fromCharCode(186),X0=360,Y0=200,t=0,dt=1/60,dtInitial=dt,dtSlow=dt,factor=.5,playMovie=!1,framePlay=!1,xScale=40,yScale=-xScale,vScale=7.5,scaleF=1.25,vectorScale=1,valuesText=new createjs.Text("","12px Trebuchet MS");valuesText.set({x:360,y:375});valuesText.set({textAlign:"center"});
var sText="",X=360,Y=200,SMALL_MASS=.1,MEDIUM_MASS=1,LARGE_MASS=25,MEDIUM_b=3,LARGE_b=5,x,y,vx,vy,m=4,b=3,g=10,drawForce=!0,index,startIndex,forceIsAct,_xmouse,_ymouse,grid=new createjs.Shape,graphX_mc=new createjs.Shape,point_mc=makeDragPoint("#FFFF99","point_mc",3),FVec=createVector("#009900",!1,!1),FText=FTextShape(),TVec=createVector("#ff0000",!1,!1),TText=TTextShape(),vVec=createVector("#0000ff",!1,!1),vText=vTextShape(),forceBeforeStop,circle=new createjs.Shape,clickArea=new createjs.Shape;
clickArea.hitArea=new createjs.Shape;clickArea.hitArea.graphics.f("#fff").dr(0,0,720,400);clickArea.addEventListener("mousedown",mouseDownGen);clickArea.addEventListener("pressup",pressUpGen);clickArea.mouseChildren=!1;
function init(){stage=new createjs.Stage(document.getElementById("demoCanvas"));createjs.Touch.enable(stage);stage.enableMouseOver();stage.enableDOMEvents(!0);canvas=document.getElementById("demoCanvas");self=stage;controlBoxContainer=new createjs.Container;self.addChild(controlBoxContainer);var a=new createjs.DOMElement("foo");controlBoxContainer.addChild(a);controlBoxContainer.x=2.5;controlBoxContainer.y=2.5;stage.addChild(clickArea);stage.addChild(graphX_mc);stage.addChild(valuesText);stage.addChild(circle);
stage.addChild(vVec);stage.addChild(vText);stage.addChild(FVec);stage.addChild(FText);stage.addChild(TVec);stage.addChild(TText);stage.addChild(point_mc);createRegister();stage.addChild(\u03a8);addFunction();showHideVariables();handleComplete();initialize();createjs.Ticker.timingMode=createjs.Ticker.RAF;createjs.Ticker.addEventListener("tick",tick);canvas.style.visibility="visible";document.getElementById("variables").style.visibility="visible"}
function initialize(){stageUpdateFlag=forceIsAct=playMovie=!1;restart()}function restart(){isOk||stage.removeAllChildren();vy=vx=y=x=t=0;X=X0+x*xScale;Y=Y0+y*yScale;clearGraph();positions()}function tick(a){playMovie&&(RungeKutta(),t+=dt,positions())}function positions(){X=X0+x*xScale;Y=Y0+y*yScale;point_mc.x=X;point_mc.y=Y;playMovie&&graphX_mc.graphics.lt(X,Y);drawVectors();stage.update()};