/*!
* © by Sitsanlis Ilias
* This notice shall be included in all copies or substantial portions of the Software.
* Creative Commons 4.0/CC BY - NC - SA 4.0. 
*/

function round(a,c){return Number(a.toFixed(c))}function fixPeriod(a,c){return a-c*Math.floor(a/c)}function rnd(a,c){return Math.floor(Math.random()*(c-a+1))+a}function toExp(a){var c=a.toExponential(1),d=c.indexOf("e");a=c.substr(0,d);var f=c.substr(d+2),e="";c=c.substr(d+1,1);for(d=0;d<=f.length-1;d++){var g=f.substr(d,1);if("0"==g)return a;e="1"==g?e+"\u00b9":"2"==g?e+"\u00b2":"3"==g?e+"\u00b3":e+String.fromCharCode("0x207"+g)}return a+"\u00b710"+("-"==c?"\u207b":"")+e}
function sngNumber(a){return 0>=a?a.toString():"+"+a.toString()}function createGrid(a,c,d,f,e,g,k,n){var h=grid.graphics;h.setStrokeStyle(.2);h.beginStroke("#666666");for(var l=0;l<=d;l+=e)h.moveTo(a+l,c),h.lineTo(a+l,c+f);for(e=0;e<=f;e+=g)h.moveTo(a,c+e),h.lineTo(a+d,c+e);h.endStroke();h.setStrokeStyle(.3);h.beginStroke("#444444");for(l=0;l<=d;l+=k)h.moveTo(a+l,c),h.lineTo(a+l,c+f);for(e=0;e<=f;e+=n)h.moveTo(a,c+e),h.lineTo(a+d,c+e);h.endStroke()}
function makeDragLine(a,c,d){void 0==a&&(a="#000000");void 0==c&&(c="dragPoint");void 0==d&&(d=100);var f=new createjs.Shape,e=f.graphics;e.setStrokeStyle(2);e.beginStroke(a);e.mt(0,0).lt(0,d);e.endStroke();e.endFill();f.hitArea=new createjs.Shape;f.hitArea.graphics.setStrokeStyle(2);f.hitArea.graphics.beginStroke("#FFFFFF");f.hitArea.graphics.beginFill("#FFFFFF");f.hitArea.graphics.dr(-20,0,40,d);f.hitArea.graphics.endFill();f.hitArea.graphics.endStroke();f.hitArea.alpha=.1;f.name=c;return f}
function makeDragPoint(a,c,d){void 0==a&&(a="#000000");void 0==c&&(c="dragPoint");void 0==d&&(d=5);var f=new createjs.Shape,e=f.graphics;e.setStrokeStyle(1);e.beginStroke("#000");e.beginFill(a);e.dc(0,0,d);e.endStroke();e.endFill();f.hitArea=new createjs.Shape;f.hitArea.graphics.beginStroke("#FFFFFF");f.hitArea.graphics.beginFill("#FFFFFF");f.hitArea.graphics.dc(0,0,20);f.hitArea.graphics.endStroke();f.hitArea.alpha=.01;f.name=c;return f}
function makePoint(a,c,d){void 0==a&&(a="#000000");void 0==c&&(c="dragPoint");void 0==d&&(d=5);var f=new createjs.Shape,e=f.graphics;e.setStrokeStyle(1);e.beginStroke(a);e.beginFill(a);e.dc(0,0,d);e.endStroke();e.endFill();f.name=c;return f}
function createVector(a,c,d){void 0==a&&(a="#000000");void 0==c&&(c=!1);void 0==d&&(d=!1);var f=new createjs.Container;new createjs.Shape;var e=createLineVector(a);f.addChild(e);new createjs.Shape;e=createArrowVector(a);f.addChild(e);c&&(new createjs.Shape,c=createDragLineVector(),f.addChild(c));d&&(new createjs.Shape,a=createCircleVector(a),f.addChild(a));return f}
function createLineVector(a){void 0==a&&(a="#000000");var c=new createjs.Shape,d=c.graphics;d.setStrokeStyle(2.5);d.beginStroke(a);d.moveTo(0,0);d.lineTo(100,0);d.endStroke();return c}function createDragLineVector(){var a=new createjs.Shape,c=a.graphics;c.setStrokeStyle(25);c.beginStroke("#ffffff");c.moveTo(0,0);c.lineTo(100,0);c.endStroke();a.alpha=.01;a.name="dragLine";return a}
function createCircleVector(a){a=new createjs.Shape;var c=a.graphics;c.beginFill("#000000");c.dc(0,0,3);a.name="startVector";a.hitArea=new createjs.Shape;a.hitArea.graphics.beginFill("#FFFFFF");a.hitArea.graphics.dc(0,0,10);return a}
function createArrowVector(a){void 0==a&&(a="#000000");var c=new createjs.Shape,d=c.graphics;d.setStrokeStyle(1.5,"round","round");d.beginStroke(a);d.beginFill(a);d.moveTo(0,0);d.lineTo(8*Math.cos(155*toRad),-8*Math.sin(155*toRad));d.lineTo(-5.5,0);d.lineTo(8*Math.cos(205*toRad),-8*Math.sin(205*toRad));d.closePath();d.endFill();d.endStroke();return c}
createjs.Container.prototype.setScaleX=function(a){var c=this.getChildAt(0),d=this.getChildAt(1),f=this.getChildByName("dragLine");this.getChildByName("startVector");d.x=a;var e=0>a?-1:1;25<=Math.abs(a)?(d.scaleX=e,c.scaleX=(a-e)/100,null!=f&&(f.scaleX=(a-e)/100)):(d.scaleX=4*a/100,c.scaleX=a/100-4*a/100/100,null!=f&&(f.scaleX=a/100-4*a/100/100))};
function updateTextVector(a,c,d,f){var e=c.rotation;arrowVec=c.getChildAt(1);var g=arrowVec.x;0>g&&(g=Math.abs(g),e+=180);g=Math.abs(g);var k=c.y+g*Math.sin(e*toRad)+d*Math.sin(e*toRad)+f*Math.sin((e+90)*toRad);a.x=c.x+g*Math.cos(e*toRad)+d*Math.cos(e*toRad)+f*Math.cos((e+90)*toRad);a.y=k;a.textBaseline="alphabetic";a.textAlign="center";a.alpha=5>Math.abs(g)?0:1}
function mouseDownVector(a){a.target.offset={x:a.target.x-720/canvas.width*a.stageX,y:a.target.y-420/canvas.height*a.stageY};a.target.addEventListener("pressmove",pressMoveVector);arc_mc.graphics.clear();\u03b8Text.visible=!1}function pressMoveVector(a){var c=720/canvas.width*a.stageX-a.target.x;a=420/canvas.height*a.stageY-a.target.y;var d=Math.atan2(-a,c)*toDeg;drVec.setScaleX(Math.sqrt(c*c+a*a));drVec.rotation=-d;updateTextVector(drText,drVec,17,0);stage.update()}
function pressUpVector(a){var c=point_mc.globalToLocal(stage.mouseX,stage.mouseY);20>Math.sqrt(c.x*c.x+c.y*c.y)?drawDr():(drVec.setScaleX(0),updateTextVector(drText,drVec,17,0));stage.update();a.target.removeEventListener("pressmove",pressMoveVector)}createjs.Shape.prototype.addArrow=function(a,c,d,f){var e=this.graphics;e.ss(1);e.s(a);e.mt(c,d).lt(c+5*Math.cos((155+f)*toRad),d-5*Math.sin((155+f)*toRad)).mt(c,d).lt(c+5*Math.cos((205+f)*toRad),d-5*Math.sin((205+f)*toRad))};
function calcF(a,c,d,f,e){if(forceIsAct){e=X0+a*xScale;var g=Y0+c*yScale;a=Math.atan2((_ymouse-Y0)/yScale-c,(_xmouse-X0)/xScale-a);c=Math.sqrt((e-_xmouse)*(e-_xmouse)+(g-_ymouse)*(g-_ymouse))/2;e=c*Math.cos(a);g=c*Math.sin(a);var k=(Math.cos(a)*d+Math.sin(a)*f)/Math.sqrt(d*d+f*f);var n=c*Math.sqrt(1-k*k);k*=c;var h=Math.atan2(f,d);h+=Math.PI/2;0>d*g-f*e&&(h+=Math.PI)}else h=k=n=g=e=a=c=0;d={};d.Fx=e;d.Fy=g;d.F=c;d.\u03c6=a;d.Fk=n;d.Fe=k;d.\u03b8=h;return d}
RungeKutta=function(){var a=fr1(x,y,vx,vy,t),c=fr2(x,y,vx,vy,t),d=fr3(x,y,vx,vy,t),f=fr4(x,y,vx,vy,t),e=fr1(x+dt*a/2,y+dt*c/2,vx+dt*d/2,vy+dt*f/2,t+dt/2),g=fr2(x+dt*a/2,y+dt*c/2,vx+dt*d/2,vy+dt*f/2,t+dt/2),k=fr3(x+dt*a/2,y+dt*c/2,vx+dt*d/2,vy+dt*f/2,t+dt/2),n=fr4(x+dt*a/2,y+dt*c/2,vx+dt*d/2,vy+dt*f/2,t+dt/2),h=fr1(x+dt*e/2,y+dt*g/2,vx+dt*k/2,vy+dt*n/2,t+dt/2),l=fr2(x+dt*e/2,y+dt*g/2,vx+dt*k/2,vy+dt*n/2,t+dt/2),p=fr3(x+dt*e/2,y+dt*g/2,vx+dt*k/2,vy+dt*n/2,t+dt/2),q=fr4(x+dt*e/2,y+dt*g/2,vx+dt*k/2,vy+
dt*n/2,t+dt/2),r=fr1(x+dt*h,y+dt*l,vx+dt*p,vy+dt*q,t+dt),u=fr2(x+dt*h,y+dt*l,vx+dt*p,vy+dt*q,t+dt),v=fr3(x+dt*h,y+dt*l,vx+dt*p,vy+dt*q,t+dt),w=fr4(x+dt*h,y+dt*l,vx+dt*p,vy+dt*q,t+dt);x+=dt*(a+2*e+2*h+r)/6;y+=dt*(c+2*g+2*l+u)/6;vx+=dt*(d+2*k+2*p+v)/6;vy+=dt*(f+2*n+2*q+w)/6};fr1=function(a,c,d,f,e){return d};fr2=function(a,c,d,f,e){return f};fr3=function(a,c,d,f,e){return(calcF(a,c,d,f,e).Fx+-b*d)/m};fr4=function(a,c,d,f,e){return(calcF(a,c,d,f,e).Fy+-b*f)/m};
function clearGraph(){var a=graphX_mc.graphics;a.clear();a.moveTo(X,Y);a.beginStroke("#FF8888");a.setStrokeStyle(2.5)}function showCircle(){var a=Math.sqrt(vx*vx+vy*vy),c=forceIsAct;forceIsAct=forceBeforeStop;var d=calcF(x,y,vx,vy,t);forceIsAct=c;a=m*a*a/d.Fk;c=d.\u03b8;d=X+a*xScale*Math.cos(c);c=Y+a*yScale*Math.sin(c);isNaN(a)||(circle.graphics.clear().ss(1).s("#666").dc(d,c,a*xScale).f("#000").dc(d,c,3),stage.update())}
function drawVectors(){vVec.setScaleX(Math.sqrt(vx*vx+vy*vy)*vScale*vectorScale);vVec.rotation=-Math.atan2(vy,vx)*toDeg;vVec.x=X;vVec.y=Y;updateTextVector(vText,vVec,12,0);var a=calcF(x,y,vx,vy,t);drawForce&&(FVec.setScaleX(Math.sqrt(a.Fx*a.Fx+a.Fy*a.Fy)*scaleF*vectorScale),FVec.rotation=-Math.atan2(a.Fy,a.Fx)*toDeg,FVec.x=X,FVec.y=Y,updateTextVector(FText,FVec,12,0));a=-b*vx;var c=-b*vy;TVec.setScaleX(Math.sqrt(a*a+c*c)*scaleF*vectorScale);TVec.x=X;TVec.y=Y;TVec.rotation=-Math.atan2(c,a)*toDeg;updateTextVector(TText,
TVec,2,10);drawForce=!0};