/*!
* © by Sitsanlis Ilias
* This notice shall be included in all copies or substantial portions of the Software.
* Creative Commons 4.0/CC BY - NC - SA 4.0. 
*/

function FTextShape() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AgpA2IABgCIAGgBIAEgCIAEgKIANgvIADgJIgBgDIgDgCIgFAAIAAgCIA9AAIgGAUIgCAAIABgGQgBgEgCgCQgCgCgDgBIgLgBIgQAAIgIAeIAJAAQAHAAAEgCQAEgCADgGIACAAIgIAcIgCAAIABgGQAAgDgDgCQgCgCgHAAIgJAAIgHAYIgCAIQAAABAAAAQAAABAAAAQABABAAAAQABAAAAABIAIABIgBACgAAXgrIgiAAIAAgEIAiAAIgDgGIARAIIgRAJg");
	
	return shape
}

function TTextShape() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AgiA2IAAgCIACAAQAEAAADgBIADgEIAEgLIARg4IgFAAQgHAAgEACQgEACgDADQgDADgBAHIgDAAIAGgWIA8AAIgHAWIgCAAIABgJQAAgEgCgCQgCgCgJAAIgGAAIgPA2IgDANQAAAAAAABQAAAAAAABQABABAAAAQAAAAABABQACABAFAAIABAAIAAACgAASgrIgiAAIAAgEIAiAAIgCgGIARAIIgRAJg");
	
	return shape
}


function vTextShape() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AgKAoQgEgBgDgEQgDgDAAgEQgBgEACgEIACgJIAEgKQACgEgBgDQAAgBAAgBQAAAAgBgBQAAAAAAAAQgBgBgBAAIgEACIgDAEIgDAEIgCAFIgCACIAAAAIgBgBIAAgBIACgFQABgDADgDIAEgFQADgBADAAIAFABIADAEIACAEIgBAFIgEAJIgCAJIgBAHQAAAEABADQACADACABIAHABQADAAADgCQAEgDADgEQAEgEACgFQACgFABgFQACgFgCgDQgBgEgDgCQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAIACgEIADgCQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAABABQAAAAAAABQAAAAABABQAAAAAAABIAAAGIgBAFIgCAHIgDALQgDAFgEAFIgIAHQgEACgEAAQgFABgEgCgAARgeIgiAAIAAgEIAiAAIgCgGIAQAIIgQAJg");
	
	return shape
}





