
function canonShape() {
	var shape = new createjs.Shape();
	shape.graphics.f().s("#373535").ss(1,1,1).p("AJ+jbIAABcIk4ACAi8i7QgBgBgBgBQgIgIgLAAQgLAAgHAIQgJAIAAALQAAALAJAHQAHAJALAAQALAAAIgJQAEgEACgFQABgEAAgFQAAgKgFgHgAJ6jcIr8AAQgRArgpgKAoVCPIF6j+IAUgBIAggzIGnAAIgBBhAi4ihQAsAAAOAdAE8hDIl3AAAn7DbIgGAAIhzAAAp4CSIBfAAAp4CVQgKAkAKAkAg/hCInCEd");
	
	shape.regX = 19
	shape.regY = -3
	
	return shape
}


function wheelShape() {
	var shape = new createjs.Shape();
	shape.graphics.f("#999999").s("#373535").s(1,1,1).p("AhgDmQgtgSgjgkQgigigUgtQgTguAAgzQAAgyATguQAUgtAigjQAjgiAtgUQAugTAyAAQAyAAAvATQAtAUAjAiQAiAjAUAtQATAuAAAyQAAAzgTAuQgUAtgiAiQgjAkgtASQguAUgzAAQgyAAgugUgAATBCIAABuQAZgDAYgKQAXgJATgQIhNhOQgGAEgIACgAhtCKQATAQAWAJQAYAKAaADIAAhuQgIgCgGgEgAA9AhIBNBOQAPgUAKgXQAKgXADgZIhuAAQgCAGgDAHgAiiBEQAJAXAQAUIBNhOQgDgHgCgGIhuAAQADAZAKAXgAA9ggQADAGACAIIBuAAQgDgagKgXQgKgXgPgUgAiihDQgKAXgDAaIBuAAQACgIADgGIhNhOQgQAUgJAXgAAThBQAIACAGADIBNhNQgTgPgXgKQgYgKgZgDgAhEiiQgWAKgTAPIBNBNQAGgDAIgCIAAhuQgaADgYAKg");
	
	//shape.regY = 25
	
	return shape
}

function v1TextShape() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AgXAkQgHgGABgIQAAgFACgMIAIgZIABgHQAAgBAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAgBAAQAAABgBAAIgHAJIgDgCQAMgTANAAQAHAAABAIQAAAEgDAIIgKAfQgCAIAAAFQAAAHADADQAEADAEAAQALAAAKgPQALgQAAgSQgBgWgQgCIABgEQAaAFAAAaQAAARgMAQQgNARgRAAQgLAAgGgFg");
	
	//shape.regY = 25
	
	return shape
}

function v2TextShape() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AgqA2IAIhXIABgJQAAgEgDgCQgCgCgGAAIgDAAIABgDIAqAAIgBADQgHAAgCABQgDABgBAEIgCAJIgGA/IAog4QAHgJABgEIACgEQAAAAAAgBQgBAAAAgBQAAAAAAAAQgBgBAAAAQgCgCgFAAIABgDIAgAAIgBADIgGABQgEACgEAEIgOARIg7BQg");
	
	//shape.regY = 25
	
	return shape
}

function p1TextShape() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AArBHIAAgCIAFAAIADgCIAAgIIAAglIAAgKIgBgCIgDgBIgFACIgBgCIARgIIACAAIAAA6IAAAHIACADIAHAAIAAACgAhEAhIABgCQAIgBACgCQACgCADgKIAUhDIACgJQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAAAgBgBIgDgBIgHABIAAgDIAbgEIgFASQAIgKAHgEQAGgEAHAAQAHAAAEAFQAGAGAAAIQgBASgOARQgNARgSAAIgHgBIgHgCIgGATIgBAIIABADIADACIAIABIgBACgAgOg2QgIAKgEANIgHAXQAFAGAIAAQAFAAAEgCIAIgHIAGgKIAGgOQACgIAAgIQAAgGgCgDQgEgEgEAAQgGAAgJAKg");
	
	//shape.regY = 25
	
	return shape
}


function p2TextShape() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AAbBHIAAgCQASgQAIgKQAHgLAAgIQAAgHgEgEQgEgEgGAAQgFAAgEADQgEADgCAFIgCAAQACgJAFgFQAFgFAIAAQAIAAAGAFQAGAGgBAHQAAAFgCAGQgEAIgIAJIgQARIASAAIAIgBIADgBIAEgEIACAAIgFANgAhHAhIAAgCQAIgBACgCQADgCACgKIAUhDIACgJQAAAAAAgBQAAAAAAgBQgBAAAAAAQAAgBAAAAIgEgBIgGABIAAgDIAbgEIgGASQAJgKAGgEQAHgEAGAAQAHAAAEAFQAGAGAAAIQgBASgOARQgMARgTAAIgHgBIgHgCIgFATIgCAIIABADIADACIAIABIgBACgAgSg2QgIAKgEANIgHAXQAFAGAIAAQAFAAAEgCIAIgHIAHgKIAFgOQADgIAAgIQgBgGgDgDQgCgEgEAAQgHAAgJAKg");
	
	//shape.regY = 25
	
	return shape
}