
function round(a,e){return Number(a.toFixed(e))}Math.trunc=Math.trunc||function(a){return isNaN(a)?NaN:0<a?Math.floor(a):Math.ceil(a)};function fixPeriod(a,e){return a-e*Math.floor(a/e)}function rnd(a,e){return Math.floor(Math.random()*(e-a+1))+a}
function toExp(a,e){var c=a.toExponential(e),b=c.indexOf("e"),d=c.substr(0,b),f=c.substr(b+2),g="";c=c.substr(b+1,1);for(b=0;b<=f.length-1;b++){var h=f.substr(b,1);g="1"==h?g+"\u00b9":"2"==h?g+"\u00b2":"3"==h?g+"\u00b3":g+String.fromCharCode("0x207"+h)}return"\u2070"==g?d:d+"\u00b710"+("-"==c?"\u207b":"")+g}function sngNumber(a){return 0>=a?a.toString():"+"+a.toString()}var shifted=!1;$(document).on("keyup keydown",function(a){shifted=a.shiftKey});
function makeDragLine(a,e,c){void 0==a&&(a="#000000");void 0==e&&(e="dragPoint");void 0==c&&(c=100);var b=new createjs.Shape,d=b.graphics;d.setStrokeStyle(2);d.beginStroke(a);d.mt(0,0).lt(0,c);d.endStroke();d.endFill();b.hitArea=new createjs.Shape;b.hitArea.graphics.setStrokeStyle(2);b.hitArea.graphics.beginStroke("#FFFFFF");b.hitArea.graphics.beginFill("#FFFFFF");b.hitArea.graphics.dr(-20,0,40,c);b.hitArea.graphics.endFill();b.hitArea.graphics.endStroke();b.hitArea.alpha=.1;b.name=e;return b}
function makeDragPoint(a,e,c){void 0==a&&(a="#000000");void 0==e&&(e="dragPoint");void 0==c&&(c=5);var b=new createjs.Shape,d=b.graphics;d.setStrokeStyle(1);d.beginStroke(a);d.beginFill(a);d.dc(0,0,c);d.endStroke();d.endFill();b.hitArea=new createjs.Shape;b.hitArea.graphics.beginStroke("#FFFFFF");b.hitArea.graphics.beginFill("#FFFFFF");b.hitArea.graphics.dc(0,0,20);b.hitArea.graphics.endStroke();b.hitArea.alpha=.01;b.name=e;return b}
function makePoint(a,e){void 0==a&&(a="#000");void 0==e&&(e=5);var c=new createjs.Shape;c.graphics.s(a).f("#FFF").ss(1).dc(0,0,e);return c}
function createVector(a,e,c){void 0==a&&(a="#000000");void 0==e&&(e=!1);void 0==c&&(c=!1);var b=new createjs.Container;new createjs.Shape;var d=createLineVector(a);b.addChild(d);new createjs.Shape;d=createArrowVector(a);b.addChild(d);e&&(new createjs.Shape,e=createDragLineVector(),b.addChild(e));c&&(new createjs.Shape,a=createCircleVector(a),b.addChild(a));return b}
function createLineVector(a){void 0==a&&(a="#000000");var e=new createjs.Shape,c=e.graphics;c.setStrokeStyle(2.5);c.beginStroke(a);c.moveTo(0,0);c.lineTo(100,0);c.endStroke();return e}function createDragLineVector(){var a=new createjs.Shape,e=a.graphics;e.setStrokeStyle(25);e.beginStroke("#ffffff");e.moveTo(0,0);e.lineTo(100,0);e.endStroke();a.alpha=.01;a.name="dragLine";return a}
function createCircleVector(a){a=new createjs.Shape;var e=a.graphics;e.beginFill("#000000");e.dc(0,0,3);a.name="startVector";return a}function createArrowVector(a){void 0==a&&(a="#000000");var e=new createjs.Shape,c=e.graphics;c.setStrokeStyle(1.5,"round","round");c.beginStroke(a);c.beginFill(a);c.moveTo(0,0);c.lineTo(8*Math.cos(155*toRad),-8*Math.sin(155*toRad));c.lineTo(-5.5,0);c.lineTo(8*Math.cos(205*toRad),-8*Math.sin(205*toRad));c.closePath();c.endFill();c.endStroke();return e}
createjs.Container.prototype.setScaleX=function(a){var e=this.getChildAt(0),c=this.getChildAt(1),b=this.getChildByName("dragLine");this.getChildByName("startVector");c.x=a;var d=0>a?-1:1;25<=Math.abs(a)?(c.scaleX=d,e.scaleX=(a-d)/100,null!=b&&(b.scaleX=(a-d)/100)):(c.scaleX=4*a/100,e.scaleX=a/100-4*a/100/100,null!=b&&(b.scaleX=a/100-4*a/100/100))};
function updateTextVector(a,e,c,b){var d=e.rotation,f=e.getChildAt(1).x;0>f&&(f=Math.abs(f),d+=180);f=Math.abs(f);var g=e.y+f*Math.sin(d*toRad)+c*Math.sin(d*toRad)+b*Math.sin((d+90)*toRad);a.x=e.x+f*Math.cos(d*toRad)+c*Math.cos(d*toRad)+b*Math.cos((d+90)*toRad);a.y=g;a.alpha=5>f?0:1}function mouseDownVector(a){a.target.offset={x:a.target.x-720/canvas.width*a.stageX,y:a.target.y-420/canvas.height*a.stageY};a.target.addEventListener("pressmove",pressMoveVector)}
function pressMoveVector(a){var e=420/canvas.height*a.stageY+a.target.offset.y;a.target.x=720/canvas.width*a.stageX+a.target.offset.x;a.target.y=e;restart()}function pressUpVector(a){a.target.removeEventListener("pressmove",pressMoveVector)}
createjs.Shape.prototype.drawDistance=function(a,e,c,b,d,f){void 0==a&&(a="#000000");var g=this.graphics;g.clear();var h=Math.sqrt((b-e)*(b-e)+(d-c)*(d-c));b=Math.atan2(-(d-c),b-e);2<h&&(d=8*(25<h?1:4*h/100),g.setStrokeStyle(1,"round","round"),g.beginStroke(a),g.mt(d*Math.cos(25*toRad),-d*Math.sin(25*toRad)).lt(0,0).lt(d*Math.cos(25*toRad),+d*Math.sin(25*toRad)),g.mt(0,0).lt(h,0).lt(h+d*Math.cos(155*toRad),-d*Math.sin(155*toRad)).mt(h,0).lt(h+d*Math.cos(205*toRad),-d*Math.sin(205*toRad)),g.setStrokeStyle(1),
g.setStrokeDash([2,2],2),g.beginStroke(a),g.mt(0,f/2).lt(0,-f/2),g.mt(h,f/2).lt(h,-f/2),g.endStroke(),g.beginFill("#FFFFFF"),g.dr(h/2-20,-6,40,12),this.rotation=-b*toDeg,this.regX=f*Math.cos(Math.PI/2),this.regY=-f*Math.sin(Math.PI/2),this.x=e,this.y=c)};
createjs.Container.prototype.slider=function(a){function e(h){var k=720/canvas.width*h.stageX+h.target.offset.x;0>k&&(k=0);k>a&&(k=a);t=T*(h.target.kT+k/a);calculations();positions()}var c=new createjs.Shape,b=c.graphics;this.addChild(c);b.setStrokeStyle(1);b.beginStroke("#aaa");for(var d=a/12,f=0;12>=f;f++)b.mt(f*d,-2).lt(f*d,-6);b.beginFill("#eee");b.r(0,-2,a,4);b.endFill();c.hitArea=new createjs.Shape;c.hitArea.graphics.beginStroke("#FFFFFF");c.hitArea.graphics.beginFill("#FFFFFF");c.hitArea.graphics.r(0,
-10,a,20);c.hitArea.graphics.endStroke();c.hitArea.alpha=.01;d=new createjs.Shape;this.addChild(d);b=d.graphics;b.setStrokeStyle(1);b.beginStroke("#aaa");b.beginFill("#eee");b.r(-4,-4,8,8);d.hitArea=new createjs.Shape;d.hitArea.graphics.beginStroke("#FFFFFF");d.hitArea.graphics.beginFill("#FFFFFF");d.hitArea.graphics.dc(0,0,20);d.hitArea.graphics.endStroke();d.hitArea.alpha=.01;for(f=0;4>=f;f++){if(0==f)var g=new createjs.Text("0","10px Trebuchet MS","#666666");else 1==f?g=new createjs.Text("T/4",
"10px Trebuchet MS","#666666"):2==f?g=new createjs.Text("T/2","10px Trebuchet MS","#666666"):3==f?g=new createjs.Text("3T/4","10px Trebuchet MS","#666666"):4==f&&(g=new createjs.Text("T","10px Trebuchet MS","#666666"));g.set({textAlign:"center"});g.x=f*a/4;g.y=-18;this.addChild(g)}c.on("click",function(h){if(!isNaN(T)&&isFinite(T)){var k=Math.floor(t/T);t=T*(k+(720/canvas.width*h.stageX-160)/a);h=T/12;var l=t-T*k;.05>=Math.abs(l-h*Math.round(l/h))&&(t=T*k+Math.round(l/h)*h);calculations();positions()}});
d.on("mousedown",function(h){!isNaN(T)&&isFinite(T)&&(h.target.offset={x:h.target.x-720/canvas.width*h.stageX,y:h.target.y-420/canvas.height*h.stageY},h.target.addEventListener("pressmove",e),h.target.kT=Math.floor(t/T))});d.on("pressup",function(h){if(!isNaN(T)&&isFinite(T)){h.target.x==a&&(h.target.x=0);if(!shifted){var k=T/12,l=t-T*h.target.kT;l=Math.abs(l-k*Math.round(l/k));1E-10>Math.abs(t-T*Math.round(t/T))?t=T*Math.round(t/T)+1E-10:l<=k/2&&(t=k*Math.round(t/k))}calculations();positions();h.target.removeEventListener("pressmove",
e)}})};createjs.Shape.prototype.addArrow=function(a,e,c,b){var d=this.graphics;d.ss(1,"round","round");d.s(a);d.mt(e,c).lt(e+6*Math.cos((150+b)*toRad),c-6*Math.sin((150+b)*toRad)).mt(e,c).lt(e+6*Math.cos((210+b)*toRad),c-6*Math.sin((210+b)*toRad))};createjs.Shape.prototype.addArrow2=function(a,e,c,b){var d=this.graphics;d.ss(2,"round","round");d.s(a);d.mt(e+7*Math.cos((155+b)*toRad),c-7*Math.sin((155+b)*toRad)).lt(e,c).lt(e+7*Math.cos((205+b)*toRad),c-7*Math.sin((205+b)*toRad))};
var mainColor="#999",secondColor="#ccc";
createjs.Container.prototype.tAxisCreate=function(a,e){var c=Math.abs(a/4).toExponential(1),b=c.indexOf("e"),d=Number(c.substr(0,b));c=Number(c.substr(b+1));d=2>d?Number("1e"+c):5>d?Number("2e"+c):Number("5e"+c);var f=0;1>d&&(f=1);this.step=d;this.removeAllChildren();c=new createjs.Shape;c.alpha=.8;this.addChild(c);c.hitArea=new createjs.Shape;c.hitArea.alpha=.01;c.hitArea.graphics.f("#000").r(0,-10,Lpx+10,20);c.graphics.s("#666").ss(1);c.graphics.ss(.5).s(secondColor);for(b=d;b<=a;b+=d){gridFlag&&
c.graphics.ss(1).s(mainColor).mt(b*e,-2*Hpx).lt(b*e,0);c.graphics.ss(1).s("#666").mt(b*e,0).lt(b*e,5);var g=new createjs.Text(b.toFixed(f),"9px Trebuchet MS","#333");g.set({textAlign:"center"});g.x=b*e;g.y=8;this.addChild(g)}for(b=0;b<=a;b+=d)for(f=.2*d;f<d;f+=.2*d)b+f<a&&(gridFlag&&c.graphics.ss(.5).s(mainColor).mt((b+f)*e,-2*Hpx).lt((b+f)*e,0),c.graphics.ss(1).s("#666").mt((b+f)*e,0).lt((b+f)*e,3));c.graphics.ss(1.5).s("#666").mt(0,0).lt(Lpx+20,0).f("#666").dc(0,0,2);c.addArrow("#666",Lpx+20,0,
0)};
createjs.Container.prototype.yAxisCreate=function(a,e,c){var b=Math.abs((e-a)/4.5).toExponential(1),d=b.indexOf("e"),f=Number(b.substr(0,d));b=Number(b.substr(d+1));f=2>f?Number("1e"+b):5>f?Number("2e"+b):Number("5e"+b);d=0;1>f&&(d=1);this.step=f;this.removeAllChildren();b=new createjs.Shape;b.graphics.ss(1.5).s("#666").mt(0,a*c).lt(0,e*c-20);b.alpha=.8;for(a=0;a<=e;a+=f){0!=a&&(b.graphics.ss(1).s("#666").mt(-5,a*c).lt(0,a*c),gridFlag&&b.graphics.ss(1).s(mainColor).mt(0,a*c).lt(Lpx,a*c));var g=new createjs.Text(a.toFixed(d),
"9px Trebuchet MS","#333");g.set({textAlign:"right"});g.y=a*c-4;g.x=-8;this.addChild(g)}b.graphics.ss(.5).s(secondColor);for(a=0;a<=e;a+=f)for(d=.2*f;d<f;d+=.2*f)a+d<e&&(b.graphics.ss(1).s("#666").mt(-3,(a+d)*c).lt(0,(a+d)*c),gridFlag&&b.graphics.ss(.5).s(secondColor).mt(0,(a+d)*c).lt(Lpx,(a+d)*c));b.addArrow("#666",0,e*c-20,90);b.graphics.s("#666").ss(1);this.addChild(b)};