/*!
* © by Sitsanlis Ilias
* This notice shall be included in all copies or substantial portions of the Software.
* Creative Commons 4.0/CC BY - NC - SA 4.0. 
*/

function trackShape() {
	var shape = new createjs.Shape();
	shape.graphics.lf(["#999999","#CCCCCC","#CCCCCC","#999999"],[0,0.314,0.749,1],0,-12.5,0,12.5).s().p("AnzB9IAAj5IPnAAIAAD5g");
	shape.regX=-50
	return shape
}

function vTextShape() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AgcA+QgGgFAAgIQAAgGADgLIAIgbIABgGQAAAAAAgBQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQgBAAAAABIgIAIIgCgCQAMgSAMAAQAIAAAAAIQAAAEgDAHIgJAfQgDAJABAFQgBAGAEADQADAEAFAAQAKAAAKgQQALgPAAgUQAAgUgQgDIABgDQAaAEAAAaQAAARgNARQgMAQgSAAQgKAAgHgFgAASgyIgzAAIAAgGIAzAAIgDgKIAaANIgaAMg");
	
	return shape
}

function xTextShape() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AAGAjIgHgdQgNAYgJAGQgFAFgFAAQgEAAgCgDQgDgCAAgDQAAgDACgCQACgCADAAQADAAADADIAEACIACgBQAEgEAIgLIAJgPIgGgWQgCgGgDgCQgEgDgGAAIgFABIAAgEIAYgEQAEAFABAEQACAEAEANIAHgMIAIgIQAEgEAEgBIAEgBQAEAAACACQADACAAADQAAABAAABQAAAAgBABQAAAAAAABQAAAAgBABQgCACgDAAIgEgBIgGgBQgCAAgDACQgFAFgIANIAHAdQACAHABABIACACQABAAAAAAQABgBAAAAQABAAABAAQAAgBABAAQAEgEAEgHIADACQgGAKgIAHQgFAEgDAAQgFAAgDgGg");
	
	return shape
}

function FVecTextShape() {
	var shape = new createjs.Shape();
	shape.graphics.f("#000000").s().p("AgpA2IABgCIAGgBIAEgCIAEgKIANgvIADgJIgBgDIgDgCIgFAAIAAgCIA9AAIgGAUIgCAAIABgGQgBgEgCgCQgCgCgDgBIgLgBIgQAAIgIAeIAJAAQAHAAAEgCQAEgCADgGIACAAIgIAcIgCAAIABgGQAAgDgDgCQgCgCgHAAIgJAAIgHAYIgCAIQAAABAAAAQAAABAAAAQABABAAAAQABAAAAABIAIABIgBACgAAXgrIgiAAIAAgEIAiAAIgDgGIARAIIgRAJg");
	
	shape.hitArea = new createjs.Shape()
	shape.hitArea.graphics.f("#FFF").dc(0,0,25)
	
	return shape
}

function KTextShape() {
	var res = new createjs.Container();
	var shape = new createjs.Shape();
	
	shape.graphics.f().s("#000000").ss(0.5,1,1).p("AhYAAICxAA");
	//shape.setTransform(273.4,201.7);

	var shape_1 = new createjs.Shape();
	shape_1.graphics.f("#000000").s().p("AhCEzIAAgFQAzguATgeQAVgdAAgZQAAgSgLgMQgMgMgPAAQgOgBgLAJQgMAJgFAQIgGAAQAEgbAPgOQAPgPAWAAQAXAAAQAQQAQAPAAAVQAAAPgHAPQgLAXgYAbQgjAmgJAJIAyAAIAWgBQAHgBAFgEQAFgDAEgHIAFAAIgOAlgAGQBLQgLgIgCgOQgBgKAGgUIAJgXQAEgMgDgNIgCgNIAAgGQACgGAGgEQAGgDAGAAQAKAAAFAJQAEAKgGATIgIATIgJAWQgFAPABAMQABAMAIAFQAHAGAKAAQALAAANgHQANgGANgQQAMgPAHgVQAJgZgGgPQgFgOgQgGIACgEQARAAAMAMQATATgMAiQgLAggcAVQgbAVgfAAQgTAAgLgHgAEgBOQgDgEAAgFQAAgHAGgVIANgtIAFgSIAAgGQAAgDgCgCQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQgGAAgGAGQgUATgSAgQgLAVgKAjIgWAAIAZhXQAEgOAAgFQAAgEgCgCQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAgBgBAAQgEABgGADQgIAFgOATQgOASgHAQQgEAJgNArIgWAAIAehpIABgEQAAgDgCgDQgDgCgFAAIgKABIgBgFIAxgJIgSBAQAMgWAJgLQAOgTANgHQAHgFAJAAQAHAAAFAFQAEAEAAAHQAAAIgDALIgKAjQAXgqAWgTQALgJAMAAQAGAAAFAFQAEAEAAAJQAAAJgDAJIgQA4IgFAUIABADIADABIAFgDQAIgGAHgLIAFAEIgNAPQgJAKgGAFQgHADgFAAQgGAAgDgDgAoKBOIABgGQAKgBAFgDQAEgEAAgFQAAgEgCgEIgIgPIgog9IgTBAQgFAQAAAFQAAAGAEADQAEACAQABIgCAGIhOAAIACgGQALAAAEgCQAGgCADgFQAEgGAFgSIAjh2QAEgNAAgIQAAgGgEgDQgEgDgLAAIgCAAIABgGIBKAAIgCAGQgJAAgEACQgGADgDAFQgDAFgGASIgPAzIBGg1QANgKAFgGQACgDAAgEQAAgCgCgDQgDgDgFAAIABgGIA/AAIgCAGQgKABgHADQgHAEgHAEIgcAVIg8AuIAwBKQANAUAJAGQAIAFAOAAIgBAGgAlCAkIAAgOICXAAIAAAOgAlCgRIAAgOICXAAIAAAOgAItg2IAAgDQAegbAMgRQAMgSAAgOQAAgKgGgIQgHgGgJAAQgJAAgGAEQgHAGgDAJIgDAAQACgQAJgIQAIgIANAAQAOAAAJAJQAKAIAAANQAAAJgEAIQgHAOgOAPIgaAcIAeAAIANgBQADgBADgCQADgCACgEIAEAAIgIAWgAgnhrIAAgFQAOAAAEgCQAEgDABgDQACgEAAgRIAAhpQAAgWgBgGQgBgFgDgCQgDgCgEAAQgFAAgJAEIgDgEIAvgXIAFAAIAAClQAAAQABAFQACADAEACQAEADAOAAIAAAFg");
	//shape_1.setTransform(273.8,201.3);


	res.addChild(shape_1);
	res.addChild(shape);
	
	//res.regX = 360
	//res.regY = 210
	res.scale = 0.7
	return res;
}